package kit_sim

// lane — the sim lane on a live session: the driver that turns the engine-
// free parts (input pipeline, ledgers, snapshots, reconcile) into two calls
// a game actually makes.
//
//     ksim.lane_init(&self.lane, &self.ses, size_of(Runner_Input))
//     ksim.lane_set_sim(&self.lane, self, game_sample, game_step)
//     // per spawned sim entity (from the factory / Ev_Spawned):
//     ksim.lane_track(&self.lane, id, entity, desc, owner)
//     // once per frame, beside session_tick:
//     ksim.lane_frame(&self.lane, delta)
//
// ZERO ROLE BRANCHES for the game: the same wiring runs everywhere, and the
// lane derives its role from the session. On the authority a frame pops each
// player's de-jittered input, steps the tick procs, ledgers truth, and ships
// per-client snapshot batches. On a client it samples local intent, predicts
// the same tick procs ahead of the server, ships the redundant input window,
// and reconciles arriving batches — the game's Step_Proc IS the resim proc,
// which is the whole single-player-shaped promise of this lane.
//
// It rides SES_APP like kit/comms: one tag, two message kinds inside it,
// both on the .Stream channel (tick-stamped, self-superseding — a lost one
// is worthless by the time it could be resent):
//
//     SIM_INPUT  client → host   [input window][snap ack]
//     SIM_SNAP   host → client   [snapshot batch]
//
// EVENTS, NOT CALLBACKS: handlers only file bytes into lane-owned state
// (input buffers, the pending batch); every call into game code — sample,
// step, resim — happens inside lane_frame, on the game's own stack. A batch
// arriving mid-pump can never re-enter the sim.
//
// The tick timeline is the SERVER'S. A client starts unanchored: it neither
// ticks nor sends until the first batch names the authoritative tick, then
// anchors ahead of it and lets the lead controller bend the clock from
// there — the batch header's input ack doubles as the feedback signal (how
// far the server's copy of our inputs ran ahead of its sim when the batch
// left), so the loop needs no extra wire and no clock-sync dependency.
//
// What the game's tick code may touch, the resim contract (scriptgen will
// enforce this on @(gd_tick) procs; until then it is discipline):
// predicted fields, lane_input, and per-tick derivables — never wall clocks,
// node state, or un-ledgered randomness.

import "core:math"
import knet "godot:kit/net"
import ksess "godot:kit/session"

SIM_TAG :: u8(3) // default SES_APP tag (comms holds 0, xfer holds 2)

SIM_INPUT: u8 : 0 // client → host, inside the tag
SIM_SNAP: u8 : 1 // host → client

// Fill the LOCAL player's input for `tick` into dst (input_size bytes).
// Read the device here and nowhere else — a resim never calls this.
Sample_Proc :: proc(user: rawptr, tick: u64, dst: rawptr)

// Advance the sim-lane world one tick: read inputs via lane_input, mutate
// predicted fields. Deliberately the same shape as Resim_Proc — the live
// frame and the replay run the identical proc. OPTIONAL once entities carry
// their own tick thunks (lane_track_set): entity ticks run first, in track
// order, then this world pass — the spot for cross-entity work (spawning a
// predicted projectile, resolving a contested pickup).
Step_Proc :: proc(user: rawptr, tick: u64)

// One entity's tick, generated by scriptgen from @(gd_tick) (or hand-built
// in tests): cast, decode nothing (input is already struct bytes), call the
// author's proc. `input` is the owning player's input for the tick being
// stepped — nil when no input drives this entity here (an inputless entity
// type, or a gap the author proc should coast through).
Tick_Thunk :: proc(entity: rawptr, input: rawptr, lane: ^Lane)

// Per entity TYPE: what the sim lane needs to drive it — the descriptor
// (predict subset) plus the tick entry point. scriptgen emits one per class
// with an @(gd_tick) proc: `runner_sim_set`.
Sim_Set :: struct {
	entity_desc: ^knet.Entity_Desc,
	tick:        Tick_Thunk,
	input_size:  int, // size of the tick proc's input struct (0 = inputless)
}

Lane_Config :: struct {
	hz:          int, // sim ticks per second (0 = DEFAULT_SIM_HZ, 60)
	snap_every:  int, // ticks between snapshot batches (0 = 3 → 20 Hz at 60)
	slots:       int, // ledger/ring depth in ticks (0 = 128 — covers ~2s of lead, resim, and ack round trips)
	margin:      int, // target server-side input headroom in ticks (0 = 2)
	redundancy:  int, // inputs per packet (0 = INPUT_REDUNDANCY)
	rewind_max:  int, // lag-comp rewind bound in ticks (0 = hz/4 ≈ 250ms — the favor-the-shooter ceiling)
	watch_delay: int, // how far behind the newest batch watched entities RENDER, in ticks (0 = 2×snap_every — almost always a bracketing pair)
	smooth_halflife: f64, // reconcile-correction render error half-life, seconds (0 = 0.063 — the puppet constant)
	smooth_cut: f32, // an error component past this is a deliberate cut and SNAPS, world units (0 = never cut)
}

// Host-side per-player state, created on a player's first input packet.
@(private = "file")
Lane_Peer :: struct {
	buf:   Input_Buffer,
	acked: u64, // newest snap tick they fully applied — their delta baseline
	fresh: bool, // did their input for the CURRENT tick actually arrive
}

@(private = "file")
Tracked :: struct {
	id:      knet.Net_Id,
	entity:  rawptr,
	desc:    ^knet.Entity_Desc,
	owner:   knet.Player_Id, // whose inputs drive it (rewound queries spare the shooter's own)
	hist:    ^History, // truth (host) / prediction (client-owned); nil = watched
	watched: bool, // client-side remote-owned: truth applies directly, no resim
	tick:    Tick_Thunk, // nil = the game's Step_Proc moves this entity
	has_in:  bool, // the thunk wants its owner's input (Sim_Set.input_size > 0)
	err:     []u8, // render-error blob (predict-subset layout), alloc'd on the first correction
}

Lane :: struct {
	ses:             ^ksess.Session,
	tag:             u8,
	snap_every:      int,
	slots:           int,
	margin:          int,
	redundancy:      int,
	rewind_max:      int,
	watch_delay:     int,
	watch_clock:     f64, // watched-entity render position, in fractional ticks
	smooth_halflife: f64,
	smooth_cut:      f32,
	ticker:          Sim_Ticker,

	user:            rawptr,
	sample:          Sample_Proc, // nil = this seat plays nobody (dedicated)
	step:            Step_Proc,

	tracked:         [dynamic]Tracked,
	entries:         [dynamic]Entry, // ledgered subset of tracked (host: all; client: mine)

	// client
	ring:            Input_Ring,
	rx:              Snap_Rx,
	pending:         [dynamic]u8, // newest unprocessed batch (copied out of the handler)
	pending_tick:    u64,
	input_ack:       u64, // newest input tick the server confirmed (batch header)
	anchored:        bool,

	// host
	peers:           map[knet.Player_Id]^Lane_Peer,

	step_tick:       u64, // the tick being stepped/resimmed — lane_input reads it
	scratch:         []u8, // one input's bytes for the sample proc

	// running tallies, game-readable (a resim burst is a netgraph datum)
	stat_resims:     int,
	stat_reconciles: int,
}

// Bind to a session (host or client, before or after it starts) — wiring
// survives session re-init like every pre-start hookup. `input_size` is the
// game's input struct size, identical on every peer by construction (the
// same compiled struct).
lane_init :: proc(l: ^Lane, ses: ^ksess.Session, input_size: int, tag := SIM_TAG, cfg := Lane_Config{}, allocator := context.allocator) {
	l.ses = ses
	l.tag = tag
	hz := cfg.hz > 0 ? cfg.hz : DEFAULT_SIM_HZ
	l.snap_every = cfg.snap_every > 0 ? cfg.snap_every : 3
	l.slots = cfg.slots > 0 ? cfg.slots : 128
	l.margin = cfg.margin > 0 ? cfg.margin : 2
	l.redundancy = cfg.redundancy > 0 ? cfg.redundancy : INPUT_REDUNDANCY
	l.rewind_max = cfg.rewind_max > 0 ? cfg.rewind_max : max(hz / 4, 1)
	l.watch_delay = cfg.watch_delay > 0 ? cfg.watch_delay : 2 * l.snap_every
	l.smooth_halflife = cfg.smooth_halflife > 0 ? cfg.smooth_halflife : 0.063
	l.smooth_cut = cfg.smooth_cut
	l.ticker = sim_ticker_make(hz)
	l.tracked = make([dynamic]Tracked, allocator)
	l.entries = make([dynamic]Entry, allocator)
	l.ring = input_ring_make(input_size, l.slots, allocator)
	l.rx = snap_rx_make(l.slots, allocator)
	l.pending = make([dynamic]u8, allocator)
	l.peers = make(map[knet.Player_Id]^Lane_Peer, allocator)
	l.scratch = make([]u8, input_size, allocator)
	ksess.session_app_route(ses, tag, l, lane_handle)
}

lane_destroy :: proc(l: ^Lane) {
	if l.ses != nil {
		ksess.session_app_route(l.ses, l.tag, nil, nil)
	}
	for &tr in l.tracked {
		if tr.hist != nil {
			history_destroy(tr.hist)
			free(tr.hist)
		}
		delete(tr.err)
	}
	delete(l.tracked)
	delete(l.entries)
	input_ring_destroy(&l.ring)
	snap_rx_destroy(&l.rx)
	delete(l.pending)
	for _, p in l.peers {
		input_buffer_destroy(&p.buf)
		free(p)
	}
	delete(l.peers)
	delete(l.scratch)
}

// The two game procs. `sample` may be nil on a seat that plays nobody (a
// dedicated server). `step` is the world pass; with lane_track_set entities
// it becomes optional — entity thunks carry the per-entity simulation, the
// step keeps only the cross-entity work (and may be nil when there is none).
lane_set_sim :: proc(l: ^Lane, user: rawptr, sample: Sample_Proc, step: Step_Proc) {
	l.user = user
	l.sample = sample
	l.step = step
}

// Put an entity on the sim lane — call where the entity is born on this peer
// (the factory / Ev_Spawned handler), with the owner from the spawn. The one
// role decision the lane makes lives here: the authority ledgers truth for
// everyone; a client ledgers predictions for its OWN entities and merely
// watches the rest (their truth applies straight from batches — phase-3
// smoothing will make that pretty).
lane_track :: proc(l: ^Lane, id: knet.Net_Id, entity: rawptr, desc: ^knet.Entity_Desc, owner: knet.Player_Id, allocator := context.allocator) {
	assert(predict_size(desc) > 0, "lane_track: entity predicts nothing — tag fields gd:\"replicate,predict\"")
	if l.ses.is_host {
		hist := new(History, allocator)
		hist^ = history_make(desc, l.slots, allocator)
		append(&l.tracked, Tracked{id = id, entity = entity, desc = desc, owner = owner, hist = hist})
		append(&l.entries, Entry{id = id, entity = entity, hist = hist})
		return
	}
	snap_rx_add(&l.rx, id, desc, allocator)
	if owner == l.ses.me {
		hist := new(History, allocator)
		hist^ = history_make(desc, l.slots, allocator)
		append(&l.tracked, Tracked{id = id, entity = entity, desc = desc, owner = owner, hist = hist})
		append(&l.entries, Entry{id = id, entity = entity, hist = hist})
	} else {
		append(&l.tracked, Tracked{id = id, entity = entity, desc = desc, owner = owner, watched = true})
	}
}

// lane_track with the generated Sim_Set: the entity now DRIVES ITSELF — its
// tick thunk runs every simulated tick (live and resim alike) with its
// owner's input, in track order, before the game's world pass. This is the
// call the scriptgen surface reduces the game to:
//
//     ksim.lane_track_set(&self.lane, id, runner, &runner_sim_set, owner)
//
// One input TYPE per lane: every input-driven entity's set must agree with
// lane_init's input_size (compose per-entity intent into one struct — the
// wire ships one input blob per player per tick, deliberately).
lane_track_set :: proc(l: ^Lane, id: knet.Net_Id, entity: rawptr, set: ^Sim_Set, owner: knet.Player_Id, allocator := context.allocator) {
	assert(set.tick != nil, "lane_track_set: a Sim_Set carries the tick entry point")
	assert(set.input_size == 0 || set.input_size == l.ring.size,
		"lane_track_set: one input struct per lane — this set's input size disagrees with lane_init's")
	lane_track(l, id, entity, set.entity_desc, owner, allocator)
	tr := &l.tracked[len(l.tracked) - 1]
	tr.tick = set.tick
	tr.has_in = set.input_size > 0
}

lane_untrack :: proc(l: ^Lane, id: knet.Net_Id) -> bool {
	if !l.ses.is_host {
		snap_rx_remove(&l.rx, id)
	}
	for &e, i in l.entries {
		if e.id == id {
			ordered_remove(&l.entries, i)
			break
		}
	}
	for &tr, i in l.tracked {
		if tr.id == id {
			if tr.hist != nil {
				history_destroy(tr.hist)
				free(tr.hist)
			}
			delete(tr.err)
			ordered_remove(&l.tracked, i)
			return true
		}
	}
	return false
}

// Sim-lane ownership transfer — possession, the carry, the ball changing
// hands. LOCAL state transition only: the session already broadcasts the
// authoritative Ev_Owner_Changed on the reliable lane; every peer forwards
// it here (the host too — its call is what flips whose input buffer drives
// the entity and whom rewound queries spare). On a client the entity swaps
// prediction modes: gaining it starts a fresh ledger seeded from the newest
// received truth (predictions begin next tick — a one-lead-deep resim later
// corrects the seam); losing it drops the ledger and the entity becomes
// watched, presented from batches like everyone else's.
lane_set_owner :: proc(l: ^Lane, id: knet.Net_Id, owner: knet.Player_Id, allocator := context.allocator) -> bool {
	for &tr, i in l.tracked {
		if tr.id != id {
			continue
		}
		if tr.owner == owner {
			return true
		}
		tr.owner = owner
		if l.ses.is_host {
			return true // truth ledgers don't care who steers
		}
		gaining := owner == l.ses.me
		if gaining && tr.watched {
			tr.watched = false
			tr.hist = new(History, allocator)
			tr.hist^ = history_make(tr.desc, l.slots, allocator)
			if e := find_rx_entry(&l.rx, id); e != nil {
				if blob, ok := history_read(&e.hist, l.rx.newest); ok {
					predict_restore(tr.entity, tr.desc, blob)
					history_note_bytes(tr.hist, l.ticker.tick, blob) // the seam's baseline
				}
			}
			append(&l.entries, Entry{id = id, entity = tr.entity, hist = tr.hist})
		} else if !gaining && !tr.watched {
			for &e, j in l.entries {
				if e.id == id {
					ordered_remove(&l.entries, j)
					break
				}
			}
			history_destroy(tr.hist)
			free(tr.hist)
			tr.hist = nil
			delete(tr.err)
			tr.err = nil
			tr.watched = true
		}
		_ = i
		return true
	}
	return false
}

// A departed player's input state (call it from your Ev_Player_Left handler;
// harmless to skip — an idle buffer holds a few KB until the run ends).
lane_drop_player :: proc(l: ^Lane, player: knet.Player_Id) {
	if p, ok := l.peers[player]; ok {
		input_buffer_destroy(&p.buf)
		free(p)
		delete_key(&l.peers, player)
	}
}

// The input driving `player`'s entities for the tick being stepped — valid
// ONLY inside your Step_Proc (live or resim, same answer). ok=false means no
// input exists here for that player this tick: a client asking about remote
// players (predict-self — coast them, their truth is on the way), a held
// gap on the host (the returned bytes then repeat their last real input).
lane_input :: proc(l: ^Lane, player: knet.Player_Id) -> (input: []u8, ok: bool) {
	if player == l.ses.me {
		return input_read(&l.ring, l.step_tick)
	}
	if l.ses.is_host {
		if p, found := l.peers[player]; found {
			return p.buf.held, p.fresh
		}
	}
	return nil, false
}

// The tick being stepped — for tick procs that derive per-tick values
// (ksim RNG seeds, cooldown arithmetic) without touching a wall clock.
lane_now :: proc(l: ^Lane) -> u64 {
	return l.step_tick
}

// ---------------------------------------------------------------------------
// The frame drive.

// Advance the sim lane; call once per frame beside session_tick. Returns how
// many sim ticks ran. A client returns 0 until the first batch anchors it to
// the server's timeline.
lane_frame :: proc(l: ^Lane, dt: f64) -> int {
	if l.ses.is_host {
		return host_frame(l, dt)
	}
	return client_frame(l, dt)
}

// One simulated tick, everywhere ticks happen — the live host loop, the live
// client loop, and the resim replay all funnel here so an entity can never
// behave differently between a prediction and its replay. Entity thunks
// first (track order — deterministic per peer because spawns ride the
// reliable ordered channel), then the game's world pass.
@(private = "file")
run_tick :: proc(l: ^Lane, t: u64) {
	l.step_tick = t
	for &tr in l.tracked {
		if tr.tick == nil || tr.watched {
			continue
		}
		in_ptr: rawptr
		if tr.has_in {
			if in_bytes, _ := lane_input(l, tr.owner); in_bytes != nil {
				in_ptr = raw_data(in_bytes)
			}
		}
		tr.tick(tr.entity, in_ptr, l)
	}
	if l.step != nil {
		l.step(l.user, t)
	}
}

@(private = "file")
host_frame :: proc(l: ^Lane, dt: f64) -> int {
	n := sim_ticker_advance(&l.ticker, dt)
	for t := l.ticker.tick - u64(n) + 1; t <= l.ticker.tick; t += 1 {
		if l.sample != nil {
			l.sample(l.user, t, raw_data(l.scratch))
			input_note(&l.ring, t, raw_data(l.scratch))
		}
		for _, p in l.peers {
			_, p.fresh = input_buffer_pop(&p.buf, t)
		}
		run_tick(l, t)
		note_all(l.entries[:], t)
		if t % u64(l.snap_every) == 0 {
			snap_broadcast(l, t)
		}
	}
	return n
}

// One batch per connected client, each against ITS acked baseline, carrying
// ITS input ack. The host player itself never gets one (no transport
// loopback, and it holds the truth already).
@(private = "file")
snap_broadcast :: proc(l: ^Lane, tick: u64) {
	for p in ksess.session_roster(l.ses) {
		if !p.connected || p.id == l.ses.me {
			continue
		}
		acked, input_ack := u64(0), u64(0)
		if lp, ok := l.peers[p.id]; ok {
			acked = lp.acked
			input_ack = lp.buf.newest
		}
		w := ksess.session_app_begin(l.ses, l.tag)
		knet.write_u8(w, SIM_SNAP)
		snap_write(w, l.entries[:], tick, acked, input_ack)
		ksess.session_app_flush(l.ses, p.peer, .Stream)
	}
}

@(private = "file")
client_frame :: proc(l: ^Lane, dt: f64) -> int {
	client_ingest(l)
	if !l.anchored {
		return 0
	}
	n := sim_ticker_advance(&l.ticker, dt)
	if n > 0 {
		// Fields may hold last frame's PRESENTED values (sim + decaying
		// error) — the ledger is the sim truth, so re-seed from it before
		// ticking. This one restore is what lets presentation vandalize the
		// fields freely between frames.
		head := l.ticker.tick - u64(n)
		for &e in l.entries {
			_ = history_restore(e.hist, head, e.entity)
		}
	}
	for t := l.ticker.tick - u64(n) + 1; t <= l.ticker.tick; t += 1 {
		if l.sample != nil {
			l.sample(l.user, t, raw_data(l.scratch))
			input_note(&l.ring, t, raw_data(l.scratch))
		}
		run_tick(l, t)
		note_all(l.entries[:], t)
	}
	if n > 0 && l.sample != nil {
		w := ksess.session_app_begin(l.ses, l.tag)
		knet.write_u8(w, SIM_INPUT)
		input_write(w, &l.ring, l.input_ack, l.redundancy)
		snap_ack_write(w, &l.rx)
		ksess.session_app_flush(l.ses, ksess.HOST_PEER, .Stream)
	}
	return n
}

// Process the newest batch the handler filed: anchor or reconcile the
// predicted set, land watched truth, and bend the clock off the ack echo.
@(private = "file")
client_ingest :: proc(l: ^Lane) {
	if len(l.pending) == 0 {
		return
	}
	truths := make([dynamic]Truth, context.temp_allocator)
	r := knet.reader_make(l.pending[:])
	tick, input_ack, _ := snap_rx_apply(&l.rx, &r, &truths)
	clear(&l.pending)
	l.pending_tick = 0
	if tick == 0 {
		return
	}
	l.input_ack = input_ack

	if !l.anchored {
		// First contact: adopt the truth outright and start predicting a
		// margin ahead of the tick the server just showed us — the lead
		// controller trims from there.
		for tr in truths {
			apply_truth(l, tr)
			if e := find_lane_entry(l, tr.id); e != nil {
				history_note_bytes(e.hist, tick, tr.blob)
			}
		}
		l.ticker.tick = tick + u64(l.margin) + 1
		l.anchored = true
		return
	}

	l.stat_reconciles += 1
	// What the screen last showed, per predicted entity — the continuity a
	// correction must glide from. Fields hold last present's visual (or the
	// sim state if the game never presents; either way, what was drawn).
	shown := make([][]u8, len(l.entries), context.temp_allocator)
	for &e, i in l.entries {
		shown[i] = make([]u8, e.hist.size, context.temp_allocator)
		predict_capture(shown[i], e.entity, e.hist.desc)
	}
	mism := make([dynamic]knet.Net_Id, context.temp_allocator)
	l.stat_resims += reconcile(l.entries[:], truths[:], tick, l.ticker.tick, l, client_resim, &mism)
	for id in mism {
		for &tr, i in l.tracked {
			if tr.id != id || tr.hist == nil {
				continue
			}
			if tr.err == nil {
				tr.err = make([]u8, tr.hist.size)
			}
			// Fields now hold the corrected head state; err = shown − truth
			// (which folds any prior error in — continuity is transitive).
			truth_now := make([]u8, tr.hist.size, context.temp_allocator)
			predict_capture(truth_now, tr.entity, tr.desc)
			for &e, j in l.entries {
				if e.id == id {
					predict_error(tr.err, shown[j], truth_now, tr.desc, l.smooth_cut)
					break
				}
			}
			break
		}
	}
	for tr in truths {
		if find_lane_entry(l, tr.id) == nil {
			apply_truth(l, tr) // watched: the server's word lands as-is
		}
	}

	// input_ack − tick = how far our inputs ran ahead of the server's sim
	// when this batch left: the observed lead. Bend toward the target.
	observed := f64(i64(input_ack) - i64(tick))
	lead_control(&l.ticker, f64(l.margin) - observed)
}

@(private = "file")
client_resim :: proc(user: rawptr, tick: u64) {
	l := cast(^Lane)user
	run_tick(l, tick) // the SAME tick path as the live frame — no sampling, no sends
}

@(private = "file")
apply_truth :: proc(l: ^Lane, tr: Truth) {
	for &t in l.tracked {
		if t.id == tr.id {
			predict_restore(t.entity, t.desc, tr.blob)
			return
		}
	}
}

@(private = "file")
find_lane_entry :: proc(l: ^Lane, id: knet.Net_Id) -> ^Entry {
	for &e in l.entries {
		if e.id == id {
			return &e
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Lag compensation: judge a shot where the SHOOTER saw the target.
//
// The rewind tick is DERIVED, never trusted: the shooter's newest snap ack is
// a fact (they provably applied that batch — it is their delta baseline), and
// what they rendered when they pressed fire is within a batch interval of it.
// Clamped to rewind_max, the favor-the-shooter ceiling: past it, a laggy
// shooter aims at the live world like everyone else.

// The tick a rewound query for `shooter` winds back to (host, inside a step).
lane_rewind_tick :: proc(l: ^Lane, shooter: knet.Player_Id) -> u64 {
	assert(l.ses.is_host, "lag compensation is the authority's job")
	t := l.step_tick
	if shooter == l.ses.me {
		return t // the host's own screen IS the live world
	}
	view := u64(0)
	if p, ok := l.peers[shooter]; ok {
		view = p.acked
	}
	if view == 0 || view >= t {
		return t // no confirmed view yet: judge live
	}
	floor := t > u64(l.rewind_max) ? t - u64(l.rewind_max) : 1
	return max(view, floor)
}

Rewound_Query :: proc(user: rawptr)

// Run `query` against the world as `shooter` rendered it: every tracked
// entity EXCEPT the shooter's own is wound back to lane_rewind_tick for the
// duration, then the live state returns — snapshots via the truth ledger,
// the exact same bytes the shooter's screen was drawn from. Entities whose
// ledger no longer holds the tick stay live (a fresh spawn the shooter
// couldn't have seen anyway). Host-only, inside your Step_Proc; returns the
// tick the world was judged at.
lane_rewound :: proc(l: ^Lane, shooter: knet.Player_Id, user: rawptr, query: Rewound_Query) -> u64 {
	tick := lane_rewind_tick(l, shooter)
	if tick >= l.step_tick {
		query(user)
		return l.step_tick
	}
	Wound :: struct {
		tr:   ^Tracked,
		live: []u8,
	}
	wound := make([dynamic]Wound, context.temp_allocator)
	for &tr in l.tracked {
		if tr.owner == shooter || tr.hist == nil {
			continue
		}
		if live, ok := history_rewind_begin(tr.hist, tick, tr.entity); ok {
			append(&wound, Wound{tr = &tr, live = live})
		}
	}
	query(user)
	for w in wound {
		history_rewind_end(w.tr.hist, w.tr.entity, w.live)
	}
	return tick
}

// ---------------------------------------------------------------------------
// Watched-entity presentation: the render clock for other people's avatars.
//
// Ingest lands watched truth as it arrives — correct, but stepping at the
// snap rate. lane_present renders them on a delayed tick timeline instead:
// a watch clock trails the newest applied batch by watch_delay ticks (so a
// bracketing PAIR of batches almost always exists), advances with frame
// time, and gets pulled gently toward its target — jitter becomes a slowly
// breathing delay, not a stutter. Blending honors Lerp_Kind per field
// (predict_blend); past the newest batch it clamps and HOLDS, never
// extrapolates. Call once per frame AFTER lane_frame, client-side (host and
// unanchored clients no-op). Predicted (own) entities are untouched — their
// freshness is the whole point of prediction.

lane_present :: proc(l: ^Lane, dt: f64) {
	if l.ses.is_host || !l.anchored || l.rx.applied_count == 0 {
		return
	}
	target := f64(l.rx.applied[l.rx.applied_count - 1]) - f64(l.watch_delay)
	if l.watch_clock == 0 {
		l.watch_clock = target // first frame: start on target
	}
	l.watch_clock += dt / l.ticker.dt // advance in tick units
	drift := target - l.watch_clock
	if abs(drift) > f64(2 * l.watch_delay) {
		l.watch_clock = target // a real discontinuity (stall, rejoin): cut
	} else {
		l.watch_clock += drift * 0.1 // breathe toward the target
	}

	// The OWN avatar: sim truth plus the decaying reconcile error — authority
	// snapped at ingest, the eye glides here. Restoring from the ledger first
	// makes a double present harmless (idempotent per frame).
	if l.smooth_halflife > 0 {
		k := f32(math.pow(0.5, dt / l.smooth_halflife))
		for &tr in l.tracked {
			if tr.watched || tr.hist == nil || tr.err == nil {
				continue
			}
			if !history_restore(tr.hist, l.ticker.tick, tr.entity) {
				continue
			}
			predict_error_decay(tr.err, tr.desc, k)
			predict_error_apply(tr.entity, tr.desc, tr.err)
		}
	}

	prev, next, ok := snap_rx_bracket(&l.rx, l.watch_clock)
	if !ok {
		return // fewer than two batches (or pre-window): ingest's snap stands
	}
	alpha := f32(1)
	if next > prev {
		alpha = f32((l.watch_clock - f64(prev)) / f64(next - prev))
		alpha = clamp(alpha, 0, 1)
	}
	for &tr in l.tracked {
		if !tr.watched {
			continue
		}
		e := find_rx_entry(&l.rx, tr.id)
		if e == nil {
			continue
		}
		a, aok := history_read(&e.hist, prev)
		b, bok := history_read(&e.hist, next)
		if !aok || !bok {
			continue // a skipped row at one end: hold ingest's last apply
		}
		predict_blend(tr.entity, tr.desc, a, b, alpha)
	}
}

@(private = "file")
find_rx_entry :: proc(rx: ^Snap_Rx, id: knet.Net_Id) -> ^Rx_Entry {
	for &e in rx.entries {
		if e.id == id {
			return &e
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// The receive side: bytes into lane state, game code never re-entered here.

@(private = "file")
lane_handle :: proc(user: rawptr, from: knet.Player_Id, from_peer: ksess.Peer_Id, r: ^knet.Reader) {
	l := cast(^Lane)user
	kind := knet.read_u8(r)
	if r.err {
		return
	}
	switch kind {
	case SIM_INPUT:
		// Host only; the session already resolved the seat (unseated peers
		// never reach a handler with a valid `from`).
		if !l.ses.is_host || from == knet.PLAYER_ID_INVALID {
			return
		}
		p, ok := l.peers[from]
		if !ok {
			p = new(Lane_Peer)
			p.buf = input_buffer_make(l.ring.size, l.slots)
			l.peers[from] = p
		}
		input_buffer_apply(&p.buf, r)
		acked := snap_ack_read(r)
		if !r.err && acked > p.acked {
			p.acked = acked // regressions are stale reordering, not truth
		}
	case SIM_SNAP:
		// Client only, and only the authority's word counts.
		if l.ses.is_host || from_peer != ksess.HOST_PEER {
			return
		}
		rest := r.data[r.off:]
		if len(rest) < 8 {
			return
		}
		peek := knet.reader_make(rest)
		tick := knet.read_u64(&peek)
		if tick <= l.pending_tick || tick <= l.rx.newest {
			return // an older batch than one already filed/applied: superseded
		}
		clear(&l.pending)
		append(&l.pending, ..rest)
		l.pending_tick = tick
	}
}
