package scriptgen

import "core:fmt"
import "core:strings"

// Maps a Variant enum member like ".Int" to the bare token used to build cached
// constructor variable names (`_to_Int`, `_from_Int`).
ctor_tag :: proc(enum_name: string) -> string {
	return enum_name[1:] // drop leading '.'
}

// ---- replicated-field expressions (nested-replicate-fields) -------------------
//
// A replicated field is addressed by its PATH from the entity root (Replicate_Info.path):
// {"hp"} for a top-level field, {"m","x"} for one reached through a `using`/embedded
// sub-struct. These build the offset/size/type-of expressions the descriptor and the POD
// #assert consume. A length-1 path emits byte-identical output to the pre-nesting code.

// The value-type expression: {"hp"} -> `type_of(Cls{}.hp)`; {"m","x"} -> `type_of(Cls{}.m.x)`.
field_type_expr :: proc(cls: string, path: []string) -> string {
	return fmt.tprintf("type_of(%s{{}}.%s)", cls, join_path(path))
}

// The byte-offset expression. Nested paths compose per segment via `type_of` on the
// container, so no intermediate struct type is ever NAMED — the generated file needs no
// import of the sub-struct's package (works for imported bundles too):
//   {"hp"}        -> offset_of(Cls, hp)
//   {"m","x"}     -> offset_of(Cls, m) + offset_of(type_of(Cls{}.m), x)
//   {"a","b","x"} -> offset_of(Cls, a) + offset_of(type_of(Cls{}.a), b) + offset_of(type_of(Cls{}.a.b), x)
field_offset_expr :: proc(cls: string, path: []string) -> string {
	if len(path) == 1 {
		return fmt.tprintf("offset_of(%s, %s)", cls, path[0])
	}
	b := strings.builder_make()
	for seg, i in path {
		if i > 0 {strings.write_string(&b, " + ")}
		if i == 0 {
			fmt.sbprintf(&b, "offset_of(%s, %s)", cls, seg)
		} else {
			fmt.sbprintf(&b, "offset_of(type_of(%s{{}}.%s), %s)", cls, join_path(path[:i]), seg)
		}
	}
	return strings.to_string(b)
}

// ---- main emitter ------------------------------------------------------------

generate :: proc(s: ^Script) -> string {
	b := strings.builder_make()
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)

	w(&b, "// Code generated by scriptgen. DO NOT EDIT.\n")
	fmt.sbprintf(&b, "// Source: %s.odin\n", snake)
	fmt.sbprintf(&b, "package %s\n\n", s.pkg)
	w(&b, "import gd \"godot:godot\"\n")
	w(&b, "import \"godot:gdext\"\n")
	w(&b, "import rt \"godot:runtime\"\n")
	// Conditional: an unused import is a compile error, so these appear only when a
	// gd:"replicate" field needs the kit/net descriptor + the POD compile-time check
	// (commands imply replicates — parse validation enforces it — but keep the
	// condition independent for robustness).
	if len(s.replicates) > 0 || len(s.commands) > 0 || len(s.entities) > 0 {
		w(&b, "import knet \"godot:kit/net\"\n")
	}
	if len(s.replicates) > 0 {
		w(&b, "import \"base:intrinsics\"\n")
	}
	// @(gd_tick) generates the sim-lane thunk + Sim_Set (kit/sim) — and an
	// entity TABLE references a target's Sim_Set when that class ticks.
	ticked_entities := false
	for e in s.entities {
		if e.has_tick {
			ticked_entities = true
			break
		}
	}
	has_lane_wiring := s.sample.proc_name != "" || s.step.proc_name != ""
	if s.tick.proc_name != "" || len(s.block_ticks) > 0 || ticked_entities || has_lane_wiring {
		w(&b, "import ksim \"godot:kit/sim\"\n")
	}
	// entity tables (`entity=Name:id` scene fields) name ksess.Entity_Type and
	// build kboot.Entity_Kind rows; the lane wiring names ksess.Session; the
	// standard transport forwards route into netgd/ksess.
	if len(s.entities) > 0 || has_lane_wiring || len(s.std_forwards) > 0 {
		w(&b, "import ksess \"godot:kit/session\"\n")
	}
	if len(s.entities) > 0 {
		w(&b, "import kboot \"godot:kit/boot\"\n")
	}
	if len(s.std_forwards) > 0 {
		w(&b, "import netgd \"godot:kit/netgd\"\n")
	}
	// verb-composition: import each package a COMPOSED command's proc lives in (so the routed
	// thunk can name `play.gun_fire`), deduped by path. "" = the entity's own package (no import).
	// The fixed packages above are pre-seeded so a block that unusually lives in one isn't
	// double-imported.
	{
		imported := make(map[string]bool)
		imported["godot:godot"] = true
		imported["godot:kit/net"] = true
		if len(s.entities) > 0 {
			imported["godot:kit/session"] = true
			imported["godot:kit/boot"] = true
		}
		for c in s.commands {
			if c.pkg_path == "" || imported[c.pkg_path] {continue}
			imported[c.pkg_path] = true
			fmt.sbprintf(&b, "import %s %q\n", c.pkg_alias, c.pkg_path)
		}
		for m in s.methods {
			if m.pkg_path == "" || imported[m.pkg_path] {continue}
			imported[m.pkg_path] = true
			fmt.sbprintf(&b, "import %s %q\n", m.pkg_alias, m.pkg_path)
		}
		for bt in s.block_ticks {
			if bt.pkg_path == "" || imported[bt.pkg_path] {continue}
			imported[bt.pkg_path] = true
			fmt.sbprintf(&b, "import %s %q\n", bt.pkg_alias, bt.pkg_path)
		}
	}
	// The trampolines/lifecycle wrappers establish `context = rt.script_context()` before
	// calling the user's plain Odin procs. On native that is `runtime.default_context()`
	// (heap-backed); on web the core installs an engine-backed context with a working
	// temp allocator (the freestanding default context has none). See runtime/context.odin.
	w(&b, "\n")

	// ---- cached Variant constructors used by trampolines ----
	to_set, from_set := collect_ctors(s)
	// Every method/accessor trampoline opens with `_ensure_ctors()`, so its definition must
	// exist whenever ANY such trampoline is emitted — even if no arg/return needs a Variant
	// constructor (a zero-arg `@(gd_method)` on a script with no other ctor needs). In that
	// case the proc is a cheap no-op; without it the call is an undeclared-name error.
	has_trampoline := len(s.methods) > 0
	if !has_trampoline {
		for ex in s.exports {
			if ex.getter != "" || ex.setter != "" {has_trampoline = true; break}
		}
	}
	if len(to_set) > 0 || len(from_set) > 0 || has_trampoline {
		w(&b, "// ---- cached Variant constructors ----\n")
		for tag in to_set {
			fmt.sbprintf(&b, "@(private = \"file\")\n_to_%s: gdext.TypeFromVariantConstructorProc\n", tag)
		}
		for tag in from_set {
			fmt.sbprintf(&b, "@(private = \"file\")\n_from_%s: gdext.VariantFromTypeConstructorProc\n", tag)
		}
		w(&b, "@(private = \"file\")\n_ctors_ready: bool\n")
		w(&b, "@(private = \"file\")\n_ensure_ctors :: proc \"contextless\" () {\n")
		w(&b, "\tif _ctors_ready {return}\n")
		for tag in to_set {
			fmt.sbprintf(&b, "\t_to_%s = gdext.get_variant_to_type_constructor(.%s)\n", tag, tag)
		}
		for tag in from_set {
			fmt.sbprintf(&b, "\t_from_%s = gdext.get_variant_from_type_constructor(.%s)\n", tag, tag)
		}
		w(&b, "\t_ctors_ready = true\n}\n\n")
	}

	// ---- lifecycle wrappers (plain proc -> rt.Lifecycle `proc \"c\"`) ----
	for lc in s.lifecycles {
		fname := fmt.tprintf("_%s_lc_%s", snake, lc.keyword)
		if lc.keyword == "process" || lc.keyword == "physics_process" {
			fmt.sbprintf(&b, "@(private = \"file\")\n%s :: proc \"c\" (self_raw: rawptr, delta: f64) {{\n", fname)
			w(&b, "\tcontext = rt.script_context()\n")
			if lc.has_delta {
				fmt.sbprintf(&b, "\t%s(cast(^%s)self_raw, delta)\n}}\n\n", lc.proc_name, cls)
			} else {
				fmt.sbprintf(&b, "\t%s(cast(^%s)self_raw)\n}}\n\n", lc.proc_name, cls)
			}
		} else {
			fmt.sbprintf(&b, "@(private = \"file\")\n%s :: proc \"c\" (self_raw: rawptr) {{\n", fname)
			w(&b, "\tcontext = rt.script_context()\n")
			fmt.sbprintf(&b, "\t%s(cast(^%s)self_raw)\n}}\n\n", lc.proc_name, cls)
		}
	}

	// ---- method trampolines ----
	for m in s.methods {
		emit_method_trampoline(&b, s, m)
	}

	// ---- getter/setter wrappers (richer-authoring #4) ----
	for ex in s.exports {
		if ex.getter != "" || ex.setter != "" {
			emit_accessor_wrappers(&b, s, ex)
		}
	}

	// ---- typed signal emit helpers ----
	if len(s.signals) > 0 {
		emit_signal_helpers(&b, s)
	}

	// ---- backing arrays + registration ----
	emit_registration(&b, s)

	return strings.to_string(b)
}

// to_/from_ constructor tag sets needed across all methods.
collect_ctors :: proc(s: ^Script) -> (to_set: [dynamic]string, from_set: [dynamic]string) {
	add :: proc(set: ^[dynamic]string, tag: string) {
		for e in set {if e == tag {return}}
		append(set, tag)
	}
	for m in s.methods {
		for a in m.args {
			add(&to_set, ctor_tag(a.vi.enum_name))
		}
		if m.ret.kind != .Nil {
			add(&from_set, ctor_tag(m.ret.enum_name))
		}
	}
	// getter/setter wrappers (richer-authoring #4): a getter marshals field->Variant
	// (from_), a setter marshals Variant->field (to_).
	for ex in s.exports {
		if ex.getter != "" {
			add(&from_set, ctor_tag(ex.vi.enum_name))
		}
		if ex.setter != "" {
			add(&to_set, ctor_tag(ex.vi.enum_name))
		}
	}
	return
}

emit_method_trampoline :: proc(b: ^strings.Builder, s: ^Script, m: Method_Info) {
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)
	fname := fmt.tprintf("_%s_m_%s", snake, m.gd_name)

	fmt.sbprintf(b, "// %s(", m.gd_name)
	for a, i in m.args {
		if i > 0 {w(b, ", ")}
		fmt.sbprintf(b, "%s: %s", a.name, a.type_text)
	}
	w(b, ")")
	if m.ret.kind != .Nil {fmt.sbprintf(b, " -> %s", m.ret.enum_name)}
	w(b, "\n")

	fmt.sbprintf(b, "@(private = \"file\")\n%s :: proc \"c\" (self_raw: rawptr, args: [^]gdext.VariantPtr, argc: i64, ret: gdext.VariantPtr) {{\n", fname)
	// Arity guard (dll-boundary defense in depth; the core's inst_call checks too): the
	// unpack below reads exactly this many Variants — a short call must not read past them.
	if len(m.args) > 0 {
		fmt.sbprintf(b, "\tif argc < %d {{return}}\n", len(m.args))
	}
	w(b, "\tcontext = rt.script_context()\n")
	w(b, "\t_ensure_ctors()\n")
	fmt.sbprintf(b, "\tself := cast(^%s)self_raw\n", cls)

	// Unpack args.
	call_args := make([dynamic]string)
	for a, i in m.args {
		tag := ctor_tag(a.vi.enum_name)
		switch a.vi.kind {
		case .Int:
			fmt.sbprintf(b, "\t_a%d: i64\n\t_to_%s(&_a%d, args[%d])\n", i, tag, i, i)
			append(&call_args, fmt.tprintf("%s(_a%d)", a.type_text, i))
		case .Float:
			fmt.sbprintf(b, "\t_a%d: f64\n\t_to_%s(&_a%d, args[%d])\n", i, tag, i, i)
			append(&call_args, fmt.tprintf("%s(_a%d)", a.type_text, i))
		case .Bool:
			fmt.sbprintf(b, "\t_a%d: bool\n\t_to_%s(&_a%d, args[%d])\n", i, tag, i, i)
			append(&call_args, fmt.tprintf("_a%d", i))
		case .Other:
			fmt.sbprintf(b, "\t_a%d: %s\n\t_to_%s(&_a%d, args[%d])\n", i, a.type_text, tag, i, i)
			append(&call_args, fmt.tprintf("_a%d", i))
		case .Nil:
		}
	}

	// Call the user proc. A composed block method routes into &self.<path>, qualifies the proc with
	// its package, and (if it declared one) passes `self` as the owner; a direct method runs `self`.
	args_joined := strings.join(call_args[:], ", ")
	defer delete(args_joined)
	recv := len(m.path) > 0 ? fmt.tprintf("&self.%s", join_path(m.path)) : "self"
	qual := m.pkg_alias != "" ? fmt.tprintf("%s.", m.pkg_alias) : ""
	prefix := recv
	if m.owner {prefix = fmt.tprintf("%s, self", prefix)} // the block asked for its wielder
	if len(call_args) > 0 {prefix = fmt.tprintf("%s, %s", prefix, args_joined)}
	if m.ret.kind == .Nil {
		fmt.sbprintf(b, "\t%s%s(%s)\n", qual, m.proc_name, prefix)
	} else {
		fmt.sbprintf(b, "\t_r := %s%s(%s)\n", qual, m.proc_name, prefix)
		tag := ctor_tag(m.ret.enum_name)
		switch m.ret.kind {
		case .Int:
			fmt.sbprintf(b, "\t_rv := i64(_r)\n\t_from_%s(ret, &_rv)\n", tag)
		case .Float:
			fmt.sbprintf(b, "\t_rv := f64(_r)\n\t_from_%s(ret, &_rv)\n", tag)
		case .Bool, .Other:
			fmt.sbprintf(b, "\t_rv := _r\n\t_from_%s(ret, &_rv)\n", tag)
		case .Nil:
		}
	}
	w(b, "}\n\n")
}

// Getter/setter wrappers (richer-authoring #4). A getter wrapper marshals the author's
// `get_<x>(self) -> V` result into the out-Variant; a setter wrapper unpacks the in-Variant
// into a typed value and calls `set_<x>(self, v)`. These are the proc ptrs the core's
// inst_get/inst_set call instead of raw field access. Marshalling mirrors the method
// trampoline's arg/return conventions.
emit_accessor_wrappers :: proc(b: ^strings.Builder, s: ^Script, ex: Export_Info) {
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)
	tag := ctor_tag(ex.vi.enum_name)

	if ex.getter != "" {
		fmt.sbprintf(b, "// getter for @export `%s` -> %s\n", ex.name, ex.getter)
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_get_%s :: proc \"c\" (self_raw: rawptr, ret: gdext.VariantPtr) {{\n", snake, ex.name)
		w(b, "\tcontext = rt.script_context()\n")
		w(b, "\t_ensure_ctors()\n")
		fmt.sbprintf(b, "\tself := cast(^%s)self_raw\n", cls)
		fmt.sbprintf(b, "\t_r := %s(self)\n", ex.getter)
		switch ex.vi.kind {
		case .Int:
			fmt.sbprintf(b, "\t_rv := i64(_r)\n\t_from_%s(ret, &_rv)\n", tag)
		case .Float:
			fmt.sbprintf(b, "\t_rv := f64(_r)\n\t_from_%s(ret, &_rv)\n", tag)
		case .Bool, .Other:
			fmt.sbprintf(b, "\t_rv := _r\n\t_from_%s(ret, &_rv)\n", tag)
		case .Nil:
		}
		w(b, "}\n\n")
	}

	if ex.setter != "" {
		fmt.sbprintf(b, "// setter for @export `%s` -> %s\n", ex.name, ex.setter)
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_set_%s :: proc \"c\" (self_raw: rawptr, value: gdext.VariantPtr) {{\n", snake, ex.name)
		w(b, "\tcontext = rt.script_context()\n")
		w(b, "\t_ensure_ctors()\n")
		fmt.sbprintf(b, "\tself := cast(^%s)self_raw\n", cls)
		switch ex.vi.kind {
		case .Int:
			fmt.sbprintf(b, "\t_v: i64\n\t_to_%s(&_v, value)\n", tag)
			fmt.sbprintf(b, "\t%s(self, %s(_v))\n", ex.setter, ex.type_text)
		case .Float:
			fmt.sbprintf(b, "\t_v: f64\n\t_to_%s(&_v, value)\n", tag)
			fmt.sbprintf(b, "\t%s(self, %s(_v))\n", ex.setter, ex.type_text)
		case .Bool:
			fmt.sbprintf(b, "\t_v: bool\n\t_to_%s(&_v, value)\n", tag)
			fmt.sbprintf(b, "\t%s(self, _v)\n", ex.setter)
		case .Other:
			fmt.sbprintf(b, "\t_v: %s\n\t_to_%s(&_v, value)\n", ex.type_text, tag)
			fmt.sbprintf(b, "\t%s(self, _v)\n", ex.setter)
		case .Nil:
		}
		w(b, "}\n\n")
	}
}

// Typed emit helpers, one per signal FIELD: `<snake>_emit_<field>(self, payload…)`. Thin
// wrappers over the godot package's `gd.emit`/`gd.emit_args` (which own the emit_signal
// MethodBind caching + CallError handling); the value they add is the TYPED signature —
// the field name and payload types are compile-checked at every emit site. The returned
// Error surfaces a misspelled/unregistered signal; callers are free to ignore it.
emit_signal_helpers :: proc(b: ^strings.Builder, s: ^Script) {
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)

	w(b, "// ---- typed signal emit helpers (over gd.emit/gd.emit_args) ----\n")
	for sig in s.signals {
		fmt.sbprintf(b, "// emit the `%s` signal (declared by the %s.%s field) with its payload.\n", sig.name, cls, sig.name)
		fmt.sbprintf(b, "%s_emit_%s :: proc \"contextless\" (self: ^%s", snake, sig.name, cls)
		for a in sig.args {
			fmt.sbprintf(b, ", %s: %s", a.name, a.vi.native)
		}
		w(b, ") -> gd.Error {\n")
		if len(sig.args) == 0 {
			fmt.sbprintf(b, "\treturn gd.emit(self.owner, \"%s\")\n", sig.name)
		} else {
			for a, i in sig.args {
				fmt.sbprintf(b, "\t_v%d := %s\n\t_va%d := gd.variant_from(&_v%d)\n", i, a.name, i, i)
			}
			fmt.sbprintf(b, "\t_err := gd.emit_args(self.owner, \"%s\"", sig.name)
			for i in 0 ..< len(sig.args) {
				fmt.sbprintf(b, ", _va%d", i)
			}
			w(b, ")\n")
			for i in 0 ..< len(sig.args) {
				fmt.sbprintf(b, "\tgdext.variant_destroy(&_va%d)\n", i)
			}
			w(b, "\treturn _err\n")
		}
		w(b, "}\n\n")
	}
}

emit_registration :: proc(b: ^strings.Builder, s: ^Script) {
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)

	w(b, "// ---- registration ----\n")

	// Per-export field metadata reflection cannot see: source line, `///` doc, and the
	// getter/setter WRAPPER proc pointers for `get=`/`set=` tags. The Export/Onready
	// tables themselves are built at registration by the runtime reflection walk
	// (rt.register_class -> runtime/register_class.odin).
	if len(s.exports) > 0 {
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_fields := [?]rt.Field_Meta {{\n", snake)
		for ex in s.exports {
			fmt.sbprintf(b, "\t{{field = \"%s\", line = %d", ex.name, ex.line)
			if ex.doc != "" {
				// %q — user-authored text can carry quotes/backslashes.
				fmt.sbprintf(b, ", doc = %q", ex.doc)
			}
			if ex.getter != "" {
				fmt.sbprintf(b, ", getter = _%s_get_%s", snake, ex.name)
			}
			if ex.setter != "" {
				fmt.sbprintf(b, ", setter = _%s_set_%s", snake, ex.name)
			}
			w(b, "},\n")
		}
		w(b, "}\n\n")
	}

	// per-method arg-type arrays
	for m in s.methods {
		if len(m.args) == 0 {continue}
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_%s_args := [?]gdext.Variant_Type{{", snake, m.gd_name)
		for a, i in m.args {
			if i > 0 {w(b, ", ")}
			w(b, a.vi.enum_name)
		}
		w(b, "}\n")
	}
	if len(s.methods) > 0 {
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_methods := [?]rt.Method {{\n", snake)
		for m in s.methods {
			// C-shaped table: pointer + count into the static per-method arg-type array.
			// An empty arg list stays at the zero value (nil + 0).
			args_ref := ""
			if len(m.args) > 0 {
				args_ref = fmt.tprintf(
					"arg_types = raw_data(_%s_%s_args[:]), arg_types_count = %d, ",
					snake,
					m.gd_name,
					len(m.args),
				)
			}
			fmt.sbprintf(
				b,
				"\t{{name = \"%s\", trampoline = _%s_m_%s, %sreturn_type = %s}},\n",
				m.gd_name,
				snake,
				m.gd_name,
				args_ref,
				m.ret.enum_name,
			)
		}
		w(b, "}\n\n")
	}

	// (No signal tables: signals are declared by typed struct fields, so the runtime
	// reflection walk builds the rt.Signal tables itself at registration.)

	// connections (@(gd_connect="signal") declarations)
	if len(s.connections) > 0 {
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_connections := [?]rt.Connection {{\n", snake)
		for c in s.connections {
			fmt.sbprintf(b, "\t{{signal = \"%s\", method = \"%s\"}},\n", c.signal, c.method)
		}
		w(b, "}\n\n")
	}

	// rpcs (@(gd_rpc[="..."]) declarations) — per-method multiplayer RPC config.
	if len(s.rpcs) > 0 {
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_rpcs := [?]rt.Rpc {{\n", snake)
		for r in s.rpcs {
			fmt.sbprintf(
				b,
				"\t{{method = \"%s\", mode = %d, transfer = %d, call_local = %v, channel = %d}},\n",
				r.method,
				r.mode,
				r.transfer,
				r.call_local,
				r.channel,
			)
		}
		w(b, "}\n\n")
	}

	// kit/net replication descriptor (gd:"replicate" fields — friendslop toolkit).
	// The #asserts enforce the POD-only contract where the field TYPE is actually
	// known (this package's compile), failing the build with the field's name —
	// a tagged string/slice/map can never silently ship. `type_of(Cls{}.f)` is an
	// unevaluated expression: no instance is constructed.
	if len(s.replicates) > 0 {
		for r in s.replicates {
			// nearly_simple_compare = memcmp-safe layout INCLUDING floats (plain
			// simple_compare excludes them over NaN semantics — for shadow diffing,
			// bitwise is exactly right). Pointers are memcmp-safe but meaningless on
			// the wire, hence the explicit exclusion.
			te := field_type_expr(cls, r.path)
			fmt.sbprintf(
				b,
				"#assert(intrinsics.type_is_nearly_simple_compare(%s) && !intrinsics.type_is_pointer(%s) && !intrinsics.type_is_multi_pointer(%s), \"%s.%s: gd:\\\"replicate\\\" fields must be POD (ints/floats/bools/enums/vectors/fixed arrays — no strings, slices, maps, or pointers)\")\n",
				te, te, te, cls, join_path(r.path),
			)
		}
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_net_fields := [?]knet.Field_Desc {{\n", snake)
		for r in s.replicates {
			flags := ""
			switch {
			case r.interp && r.owner:
				flags = "{.Interp, .Owner_Stream}"
			case r.interp && r.predict:
				flags = "{.Interp, .Predicted}"
			case r.interp:
				flags = "{.Interp}"
			case r.owner:
				flags = "{.Owner_Stream}"
			case r.predict:
				flags = "{.Predicted}"
			case:
				flags = "{}"
			}
			lerp := len(r.lerp) > 0 ? fmt.tprintf(", lerp = %s", r.lerp) : ""
			if len(r.blend) > 0 {
				lerp = fmt.tprintf(", lerp = .Custom, blend = %s", r.blend)
			}
			wire := len(r.wire) > 0 ? fmt.tprintf(", wire = %s", r.wire) : ""
			if len(r.codec) > 0 {
				wire = fmt.tprintf(", wire = .Custom, codec = %s", r.codec)
			}
			fmt.sbprintf(
				b,
				"\t{{offset = %s, size = size_of(%s), flags = %s%s%s}},\n",
				field_offset_expr(cls, r.path), field_type_expr(cls, r.path), flags, lerp, wire,
			)
		}
		w(b, "}\n\n")
		fmt.sbprintf(
			b,
			"// kit/net replication descriptor for %s — consumed by the toolkit session layer.\n%s_net_desc := knet.Entity_Desc{{fields = _%s_net_fields[:]}}\n\n",
			cls, snake, snake,
		)
	}

	// @(gd_command) dispatch + typed issue wrappers (friendslop toolkit).
	// Three artifacts per class: decode thunks (client and host execute a command
	// from byte-identical args — the thunk decodes, checks the reader, THEN calls
	// the author's proc), the Command_Desc table, and one `<proc>_cmd` wrapper per
	// command. The wrapper holds the ONLY role branch in the entire feature:
	// authority runs the proc directly (and fires the game's command hook, the
	// same cross-entity path client commands take); clients predict (iff
	// declared) and send. A name-paired `<wrapper>_then` consequence, when the
	// game declares one, fires on the authority right after the verb applies —
	// in the thunk for received commands, in the wrapper for the host's own —
	// with the issuer, the wire args, and the verb's returned payload.
	upper := strings.to_upper(snake)
	// A class that TICKS executes its verbs inside the tick pipeline instead
	// (kit/sim command scheduling) — the knet command loop's optimistic-apply
	// and the lane's resim would otherwise fight over one baseline. Its knet
	// command table and ctx-shaped wrappers are skipped whole; the sim block
	// below emits the tick-scheduled equivalents.
	is_sim := s.tick.proc_name != "" || len(s.block_ticks) > 0
	if len(s.commands) > 0 && !is_sim {
		w(b, "// ---- @(gd_command) dispatch + typed issue wrappers ----\n\n")
		w(b, "// Command indices, by declaration order — for the game's command hook\n")
		w(b, "// dispatch (never hand-sync these; reordering procs reorders them).\n")
		for c, ci in s.commands {
			fmt.sbprintf(b, "%s_CMD_%s :: u16(%d)\n", upper, strings.to_upper(c.name), ci)
		}
		w(b, "\n")
		for c in s.commands {
			// A composed command routes into the embedded field (`&self.gun`) and qualifies the
			// proc with its package (`play.gun_fire`); a direct one runs `runner_fire(self, …)`.
			recv := len(c.path) > 0 ? fmt.tprintf("&self.%s", join_path(c.path)) : "self"
			qual := c.pkg_alias != "" ? fmt.tprintf("%s.", c.pkg_alias) : ""
			fmt.sbprintf(b, "@(private = \"file\")\n_%s_cmd_%s :: proc(entity: rawptr, r: ^knet.Reader, env: ^knet.Command_Env) -> bool {{\n", snake, c.name)
			fmt.sbprintf(b, "\tself := cast(^%s)entity\n", cls)
			for a, i in c.args {
				fmt.sbprintf(b, "\t_a%d := knet.read_%s(r)\n", i, a.wire)
			}
			w(b, "\tif r.err {return false}\n")
			// The verb call — payload returns are captured for the consequence
			// (or blanked when nothing consumes them).
			if c.then_proc == "" && c.payload_count == 0 {
				fmt.sbprintf(b, "\treturn %s%s(%s", qual, c.proc_name, recv)
				if c.owner {w(b, ", self")} // the block asked for its wielder — pass the entity
				for _, i in c.args {
					fmt.sbprintf(b, ", _a%d", i)
				}
				w(b, ")\n}\n\n")
				continue
			}
			w(b, "\t_ok")
			for i in 0 ..< c.payload_count {
				if c.then_proc != "" {
					fmt.sbprintf(b, ", _p%d", i)
				} else {
					w(b, ", _") // payload declined — the block offered, nobody consumes
				}
			}
			fmt.sbprintf(b, " := %s%s(%s", qual, c.proc_name, recv)
			if c.owner {w(b, ", self")}
			for _, i in c.args {
				fmt.sbprintf(b, ", _a%d", i)
			}
			w(b, ")\n")
			if c.then_proc != "" {
				// The consequence: authority-only, once, after the verb applied —
				// predictions and replays run this same thunk with authority=false.
				w(b, "\tif _ok && env.authority {\n")
				if c.then_game != "" {
					fmt.sbprintf(b, "\t\tassert(env.user != nil, \"%s needs the game pointer — session_set_factory's user is what consequences receive (tests: set ctx.game_user)\")\n", c.then_proc)
					fmt.sbprintf(b, "\t\t%s(cast(^%s)env.user, self, env.by", c.then_proc, c.then_game)
				} else {
					fmt.sbprintf(b, "\t\t%s(self, env.by", c.then_proc)
				}
				for _, i in c.args {
					fmt.sbprintf(b, ", _a%d", i)
				}
				for i in 0 ..< c.payload_count {
					fmt.sbprintf(b, ", _p%d", i)
				}
				w(b, ")\n\t}\n")
			}
			w(b, "\treturn _ok\n}\n\n")
		}

		fmt.sbprintf(b, "@(private = \"file\")\n_%s_commands := [?]knet.Command_Desc {{\n", snake)
		for c in s.commands {
			fmt.sbprintf(b, "\t{{name = %q, predict = %v, invoke = _%s_cmd_%s}},\n", c.name, c.predict, snake, c.name)
		}
		w(b, "}\n\n")
	}

	// The command set is emitted for EVERY entity with a descriptor — desc-only
	// entities (no commands) used to force a hand-built set in the game. A
	// ticking class's set stays desc-only: its verbs ride the lane.
	if len(s.replicates) > 0 || len(s.commands) > 0 {
		cmds := len(s.commands) > 0 && !is_sim ? fmt.tprintf(", commands = _%s_commands[:]", snake) : ""
		net_id := s.net_id_type != "" ? fmt.tprintf(", net_id_offset = int(offset_of(%s, net_id))", cls) : ""
		fmt.sbprintf(
			b,
			"// kit/net command set for %s — the command table + the replicated-field descriptor.\n%s_command_set := knet.Command_Set{{entity_desc = &%s_net_desc%s%s}}\n\n",
			cls, snake, snake, cmds, net_id,
		)
	}

	if len(s.commands) > 0 && !is_sim {
		for c, ci in s.commands {
			// A composed command routes into the block and qualifies the proc; its wrapper is
			// named per-entity (`runner_gun_fire_cmd`) so two blocks of the same type never collide.
			recv := len(c.path) > 0 ? fmt.tprintf("&self.%s", join_path(c.path)) : "self"
			qual := c.pkg_alias != "" ? fmt.tprintf("%s.", c.pkg_alias) : ""
			wrapper := len(c.path) > 0 ? fmt.tprintf("%s_%s", snake, c.name) : c.proc_name
			fmt.sbprintf(b, "// Issue `%s` — the SAME call on every peer, zero role branches. Authority:\n", c.name)
			if c.predict {
				w(b, "// runs the proc directly. Client: predicts optimistically (rejection or a lost\n")
				w(b, "// result auto-reverts the declared fields) and sends the command to the host.\n")
			} else {
				w(b, "// runs the proc directly. Client: sends the command to the host (no prediction\n")
				w(b, "// declared); the state change arrives through normal replication.\n")
			}
			w(b, "// Returns whether the command applied locally (authoritative on the host,\n")
			w(b, "// optimistic on a predicting client) — the host's result is always authoritative.\n")
			fmt.sbprintf(b, "%s_cmd :: proc(ctx: ^knet.Command_Ctx, self: ^%s", wrapper, cls)
			for a in c.args {
				fmt.sbprintf(b, ", %s: %s", a.name, a.type_text)
			}
			w(b, ") -> bool {\n")
			w(b, "\tif ctx.is_authority {\n")
			w(b, "\t\t_ok")
			for i in 0 ..< c.payload_count {
				if c.then_proc != "" {
					fmt.sbprintf(b, ", _p%d", i)
				} else {
					w(b, ", _")
				}
			}
			fmt.sbprintf(b, " := %s%s(%s", qual, c.proc_name, recv)
			if c.owner {w(b, ", self")}
			for a in c.args {
				fmt.sbprintf(b, ", %s", a.name)
			}
			w(b, ")\n")
			if c.then_proc != "" {
				// The host's own issue takes the same consequence path a client's
				// command does (fired in the receive thunk there).
				w(b, "\t\tif _ok {\n")
				if c.then_game != "" {
					fmt.sbprintf(b, "\t\t\tassert(ctx.game_user != nil, \"%s needs the game pointer — session_set_factory's user is what consequences receive (tests: set ctx.game_user)\")\n", c.then_proc)
					fmt.sbprintf(b, "\t\t\t%s(cast(^%s)ctx.game_user, self, ctx.me", c.then_proc, c.then_game)
				} else {
					fmt.sbprintf(b, "\t\t\t%s(self, ctx.me", c.then_proc)
				}
				for a in c.args {
					fmt.sbprintf(b, ", %s", a.name)
				}
				for i in 0 ..< c.payload_count {
					fmt.sbprintf(b, ", _p%d", i)
				}
				w(b, ")\n\t\t}\n")
			}
			fmt.sbprintf(b, "\t\tknet.command_hook_local(ctx, self.net_id, %d, _ok) // same cross-entity path client commands take\n", ci)
			w(b, "\t\treturn _ok\n\t}\n")
			fmt.sbprintf(b, "\tknet.command_begin(ctx, self.net_id, %d)\n", ci)
			for a in c.args {
				fmt.sbprintf(b, "\tknet.write_%s(&ctx.msg, %s)\n", a.wire, a.name)
			}
			fmt.sbprintf(b, "\treturn knet.command_issue(ctx, self, &%s_command_set, %d)\n}}\n\n", snake, ci)
		}
	}

	// ---- @(gd_tick): the sim-lane step thunk + Sim_Set (kit/sim) ----
	// The thunk is the whole bridge: the lane drives entities through rawptrs
	// (live ticks AND resim replays take the identical path), the author's
	// proc stays typed and single-player-shaped. The input struct crosses the
	// wire raw, so the same POD contract as replicated fields is #asserted at
	// the consumer compile, naming the type.
	if s.tick.proc_name != "" || len(s.block_ticks) > 0 {
		w(b, "// ---- @(gd_tick) sim-lane step ----\n\n")
		if s.tick.input_type != "" {
			fmt.sbprintf(
				b,
				"#assert(intrinsics.type_is_nearly_simple_compare(%s) && !intrinsics.type_is_pointer(%s) && !intrinsics.type_is_multi_pointer(%s), \"%s: @(gd_tick) input structs must be POD (they cross the wire raw — no strings, slices, maps, or pointers)\")\n\n",
				s.tick.input_type, s.tick.input_type, s.tick.input_type, s.tick.input_type,
			)
		}
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_tick_step :: proc(entity: rawptr, input: rawptr, lane: ^ksim.Lane, owner: knet.Player_Id) {{\n", snake)
		if s.tick.proc_name != "" && s.tick.input_type != "" {
			w(b, "\tif input == nil {return} // no input drives this entity here this tick: coast\n")
		}
		consumed := s.tick.then_proc != "" || s.tick.fx_proc != ""
		need_self := consumed || len(s.block_ticks) > 0
		if need_self {
			fmt.sbprintf(b, "\tself := cast(^%s)entity\n", cls)
		}
		if s.tick.proc_name != "" {
			if s.tick.payload_count > 0 {
				w(b, "\t")
				for i in 0 ..< s.tick.payload_count {
					if i > 0 {w(b, ", ")}
					if consumed {
						fmt.sbprintf(b, "_p%d", i)
					} else {
						w(b, "_") // payload offered, nobody consumes (warned at build)
					}
				}
				w(b, " := ")
			} else {
				w(b, "\t")
			}
			if need_self {
				fmt.sbprintf(b, "%s(self", s.tick.proc_name)
			} else {
				fmt.sbprintf(b, "%s(cast(^%s)entity", s.tick.proc_name, cls)
			}
			if s.tick.input_type != "" {
				fmt.sbprintf(b, ", (cast(^%s)input)^", s.tick.input_type)
			}
			if s.tick.wants_lane {
				w(b, ", lane")
			}
			w(b, ")\n")
		}
		// Composed block ticks, AFTER the entity's own step in field order —
		// the entity writes intent first, blocks integrate.
		for bt in s.block_ticks {
			qual := bt.pkg_alias != "" ? fmt.tprintf("%s.", bt.pkg_alias) : ""
			fmt.sbprintf(b, "\t%s%s(&self.%s", qual, bt.proc_name, join_path(bt.path))
			if bt.wants_owner {
				w(b, ", self")
			}
			if bt.wants_lane {
				w(b, ", lane")
			}
			w(b, ")\n")
		}
		// The role gates the game used to hand-write, held HERE: the
		// consequence on the authority (which never resims), the fx on the
		// owning peer's live pass only — a replay re-runs the tick, never
		// the presentation, and never double-fires a consequence.
		if s.tick.then_proc != "" {
			w(b, "\tif ksim.lane_is_authority(lane) {\n\t\t")
			if s.tick.then_game != "" {
				fmt.sbprintf(b, "assert(ksim.lane_game(lane) != nil, \"%s needs the game pointer — lane_set_sim's user is what tick consequences receive\")\n\t\t", s.tick.then_proc)
				fmt.sbprintf(b, "%s(cast(^%s)ksim.lane_game(lane), self, owner", s.tick.then_proc, s.tick.then_game)
			} else {
				fmt.sbprintf(b, "%s(self, owner", s.tick.then_proc)
			}
			for i in 0 ..< s.tick.payload_count {
				fmt.sbprintf(b, ", _p%d", i)
			}
			w(b, ")\n\t}\n")
		}
		if s.tick.fx_proc != "" {
			w(b, "\tif owner == ksim.lane_me(lane) && !lane.resimming {\n\t\t")
			if s.tick.fx_game != "" {
				fmt.sbprintf(b, "%s(cast(^%s)ksim.lane_game(lane), self", s.tick.fx_proc, s.tick.fx_game)
			} else {
				fmt.sbprintf(b, "%s(self", s.tick.fx_proc)
			}
			for i in 0 ..< s.tick.payload_count {
				fmt.sbprintf(b, ", _p%d", i)
			}
			w(b, ")\n\t}\n")
		}
		w(b, "}\n\n")
		// ---- @(gd_command) on a ticking class: tick-scheduled verbs ----
		// The verb executes INSIDE the tick pipeline on both ends (kit/sim
		// command.odin): the client speculates at its next tick and resims
		// re-apply the captured patch; the authority executes at the stamped
		// tick and its `_then` fires there — the exec thunk holds that gate.
		if len(s.commands) > 0 {
			w(b, "// Command indices, by declaration order.\n")
			for c, ci in s.commands {
				fmt.sbprintf(b, "%s_CMD_%s :: u16(%d)\n", upper, strings.to_upper(c.name), ci)
			}
			w(b, "\n")
			for c in s.commands {
				recv := len(c.path) > 0 ? fmt.tprintf("&self.%s", join_path(c.path)) : "self"
				qual := c.pkg_alias != "" ? fmt.tprintf("%s.", c.pkg_alias) : ""
				fmt.sbprintf(b, "@(private = \"file\")\n_%s_simcmd_%s :: proc(entity: rawptr, args: []u8, lane: ^ksim.Lane, by: knet.Player_Id) -> bool {{\n", snake, c.name)
				fmt.sbprintf(b, "\tself := cast(^%s)entity\n", cls)
				if len(c.args) > 0 {
					w(b, "\tr := knet.reader_make(args)\n")
					for a, i in c.args {
						fmt.sbprintf(b, "\t_a%d := knet.read_%s(&r)\n", i, a.wire)
					}
					w(b, "\tif r.err {return false}\n")
				}
				w(b, "\t_ok")
				for i in 0 ..< c.payload_count {
					if c.then_proc != "" {
						fmt.sbprintf(b, ", _p%d", i)
					} else {
						w(b, ", _")
					}
				}
				fmt.sbprintf(b, " := %s%s(%s", qual, c.proc_name, recv)
				if c.owner {w(b, ", self")}
				for _, i in c.args {
					fmt.sbprintf(b, ", _a%d", i)
				}
				w(b, ")\n")
				if c.then_proc != "" {
					w(b, "\tif _ok && ksim.lane_is_authority(lane) {\n")
					if c.then_game != "" {
						fmt.sbprintf(b, "\t\tassert(ksim.lane_game(lane) != nil, \"%s needs the game pointer — lane_set_sim's user is what consequences receive\")\n", c.then_proc)
						fmt.sbprintf(b, "\t\t%s(cast(^%s)ksim.lane_game(lane), self, by", c.then_proc, c.then_game)
					} else {
						fmt.sbprintf(b, "\t\t%s(self, by", c.then_proc)
					}
					for _, i in c.args {
						fmt.sbprintf(b, ", _a%d", i)
					}
					for i in 0 ..< c.payload_count {
						fmt.sbprintf(b, ", _p%d", i)
					}
					w(b, ")\n\t}\n")
				}
				w(b, "\treturn _ok\n}\n\n")
			}
			fmt.sbprintf(b, "@(private = \"file\")\n_%s_sim_cmds := [?]ksim.Sim_Cmd {{\n", snake)
			for c in s.commands {
				fmt.sbprintf(b, "\t{{exec = _%s_simcmd_%s}},\n", snake, c.name)
			}
			w(b, "}\n\n")
			for c, ci in s.commands {
				wrapper := len(c.path) > 0 ? fmt.tprintf("%s_%s", snake, c.name) : c.proc_name
				fmt.sbprintf(b, "// Issue `%s` — tick-scheduled on the sim lane: the SAME call on every peer,\n", c.name)
				w(b, "// zero role branches. Your own entity speculates at your next tick; the\n")
				w(b, "// authority executes at the stamped tick and answers with a verdict — a\n")
				w(b, "// rejection unwinds the delta-lane writes and the reconcile scrubs the\n")
				w(b, "// predicted ones. Returns whether it SCHEDULED; the verdict is state.\n")
				fmt.sbprintf(b, "%s_cmd :: proc(l: ^ksim.Lane, self: ^%s", wrapper, cls)
				for a in c.args {
					fmt.sbprintf(b, ", %s: %s", a.name, a.type_text)
				}
				w(b, ") -> bool {\n")
				if len(c.args) > 0 {
					w(b, "\t_w := knet.writer_make(64, context.temp_allocator)\n")
					for a in c.args {
						fmt.sbprintf(b, "\tknet.write_%s(&_w, %s)\n", a.wire, a.name)
					}
					fmt.sbprintf(b, "\treturn ksim.lane_command(l, self.net_id, %d, knet.writer_bytes(&_w))\n}}\n\n", ci)
				} else {
					fmt.sbprintf(b, "\treturn ksim.lane_command(l, self.net_id, %d, nil)\n}}\n\n", ci)
				}
			}
		}

		in_size := s.tick.input_type != "" ? fmt.tprintf("size_of(%s)", s.tick.input_type) : "0"
		contested := s.tick.contested ? ", contested = true" : ""
		sim_cmds := len(s.commands) > 0 ? fmt.tprintf(", commands = _%s_sim_cmds[:]", snake) : ""
		fmt.sbprintf(
			b,
			"// kit/sim set for %s — ksim.lane_track_set(&lane, id, self, &%s_sim_set, owner)\n%s_sim_set := ksim.Sim_Set{{entity_desc = &%s_net_desc, tick = _%s_tick_step, input_size = %s%s%s}}\n\n",
			cls, snake, snake, snake, snake, in_size, contested, sim_cmds,
		)
	}

	// ---- the standard transport forwards (a kboot.Boot field declares them) ----
	// Bodies for the Method_Info entries resolve_boot_forwards synthesized:
	// the four one-liners every session game used to copy, wired through the
	// boot's own wire/session pointers. Name-dispatched like any method, so
	// they survive hot reload; a hand-written same-name method suppressed the
	// synthesis entirely.
	for name in s.std_forwards {
		switch name {
		case "on_packet":
			fmt.sbprintf(
				b,
				"@(private = \"file\")\n_%s_std_on_packet :: proc(self: ^%s, id: gd.Int, packet: gd.Packed_Byte_Array) {{\n\tnetgd.wire_receive(&self.%s.wire, id, packet)\n}}\n\n",
				snake, cls, s.boot_field,
			)
		case "on_peer_left":
			fmt.sbprintf(
				b,
				"@(private = \"file\")\n_%s_std_on_peer_left :: proc(self: ^%s, id: gd.Int) {{\n\tif self.%s.ses == nil {{return}}\n\tksess.session_peer_disconnected(self.%s.ses, ksess.Peer_Id(id))\n}}\n\n",
				snake, cls, s.boot_field, s.boot_field,
			)
		case "on_net_up":
			fmt.sbprintf(
				b,
				"@(private = \"file\")\n_%s_std_on_net_up :: proc(self: ^%s) {{\n\tif self.%s.ses == nil {{return}}\n\tksess.session_client_join(self.%s.ses)\n}}\n\n",
				snake, cls, s.boot_field, s.boot_field,
			)
		case "on_net_down":
			fmt.sbprintf(
				b,
				"@(private = \"file\")\n_%s_std_on_net_down :: proc(self: ^%s) {{\n\tif self.%s.ses == nil {{return}}\n\tksess.session_peer_disconnected(self.%s.ses, ksess.HOST_PEER)\n}}\n\n",
				snake, cls, s.boot_field, s.boot_field,
			)
		}
	}

	// ---- @(gd_sample)/@(gd_step): the lane wiring, written by nobody ----
	// The thunks hold the rawptr casts; `<snake>_lane_init` carries the input
	// size (from the package's tick input struct — resolve_sim pinned the
	// sample to it) and the step's authority gate. Game wiring is two lines:
	// `<snake>_lane_init(self, &self.lane, &self.ses, cfg = {...})` beside
	// boot_attach, then `kboot.boot_lane(&self.boot, &self.lane)`.
	if s.sample.proc_name != "" || s.step.proc_name != "" {
		w(b, "// ---- @(gd_sample)/@(gd_step) lane wiring ----\n\n")
		if s.sample.proc_name != "" {
			fmt.sbprintf(
				b,
				"@(private = \"file\")\n_%s_lane_sample :: proc(user: rawptr, tick: u64, dst: rawptr) {{\n\t%s(cast(^%s)user, tick, cast(^%s)dst)\n}}\n\n",
				snake, s.sample.proc_name, cls, s.sample.input_type,
			)
		}
		if s.step.proc_name != "" {
			fmt.sbprintf(
				b,
				"@(private = \"file\")\n_%s_lane_step :: proc(user: rawptr, tick: u64) {{\n\t%s(cast(^%s)user, tick)\n}}\n\n",
				snake, s.step.proc_name, cls,
			)
		}
		lane_in_size := s.lane_input_type != "" ? fmt.tprintf("size_of(%s)", s.lane_input_type) : "0"
		sample_ref := s.sample.proc_name != "" ? fmt.tprintf("_%s_lane_sample", snake) : "nil"
		step_ref := s.step.proc_name != "" ? fmt.tprintf("_%s_lane_step", snake) : "nil"
		auth := s.step.authority ? "true" : "false"
		fmt.sbprintf(
			b,
			"// The lane beside the session: input size, typed sample, world pass, and\n"+
			"// the authority gate — all from the attributes. cfg tunes; zero = defaults.\n"+
			"%s_lane_init :: proc(self: ^%s, l: ^ksim.Lane, ses: ^ksess.Session, tag := ksim.SIM_TAG, cfg := ksim.Lane_Config{{}}) {{\n"+
			"\tksim.lane_init(l, ses, %s, tag, cfg)\n"+
			"\tksim.lane_set_sim(l, self, %s, %s, step_authority = %s)\n"+
			"}}\n\n",
			snake, cls, lane_in_size, sample_ref, step_ref, auth,
		)
	}

	// ---- entity kinds: `entity=Name:id` scene fields -> the kboot table ----
	// The tag on the exported PackedScene field is the whole factory
	// declaration: TYPE consts (the wire ids games used to hand-keep), typed
	// rt.script_of thunks, typed spawn/free hook thunks, and one
	// kboot.Entity_Kind row per tag. kit/boot's boot_entities drives it.
	if len(s.entities) > 0 {
		w(b, "// ---- entity kinds (gd:\"...,entity=Name:id\" scene fields) ----\n\n")
		w(b, "// The stable wire ids, named like the hand-kept consts they replace.\n")
		for e in s.entities {
			fmt.sbprintf(b, "%s_TYPE :: ksess.Entity_Type(%d)\n", strings.to_upper(to_snake(e.target)), e.type_id)
		}
		w(b, "\n")
		for e in s.entities {
			tsnake := to_snake(e.target)
			fmt.sbprintf(b, "@(private = \"file\")\n_%s_ent_make_%s :: proc(node: gd.Node) -> rawptr {{\n\treturn rt.script_of(node, %s)\n}}\n\n", snake, tsnake, e.target)
			if e.spawned != "" {
				fmt.sbprintf(b, "@(private = \"file\")\n_%s_ent_spawned_%s :: proc(game: rawptr, entity: rawptr, id: knet.Net_Id, owner: knet.Player_Id) {{\n\t%s(cast(^%s)game, cast(^%s)entity, id, owner)\n}}\n\n", snake, tsnake, e.spawned, cls, e.target)
			}
			if e.freed != "" {
				fmt.sbprintf(b, "@(private = \"file\")\n_%s_ent_freed_%s :: proc(game: rawptr, entity: rawptr, id: knet.Net_Id) {{\n\t%s(cast(^%s)game, cast(^%s)entity, id)\n}}\n\n", snake, tsnake, e.freed, cls, e.target)
			}
		}
		fmt.sbprintf(b, "// The factory table — pass to kboot.boot_entities(&self.boot, self, %s_entity_kinds[:]).\n", snake)
		fmt.sbprintf(b, "%s_entity_kinds := [?]kboot.Entity_Kind {{\n", snake)
		for e in s.entities {
			tsnake := to_snake(e.target)
			fmt.sbprintf(
				b,
				"\t{{type = %s_TYPE, name = %q, set = &%s_command_set, script_of = _%s_ent_make_%s, scene_offset = offset_of(%s, %s)",
				strings.to_upper(tsnake), e.target, tsnake, snake, tsnake, cls, e.field,
			)
			if e.spawned != "" {
				fmt.sbprintf(b, ", spawned = _%s_ent_spawned_%s", snake, tsnake)
			}
			if e.freed != "" {
				fmt.sbprintf(b, ", freed = _%s_ent_freed_%s", snake, tsnake)
			}
			if e.has_tick {
				// The class ticks: the row carries its Sim_Set, so boot_lane's
				// factory puts every spawn on the sim lane — no game code.
				fmt.sbprintf(b, ", sim_set = &%s_sim_set", tsnake)
			}
			w(b, "},\n")
		}
		w(b, "}\n\n")

		// The typed census — the registry/boot ledgers queried back, so the
		// hand-kept `map[Net_Id]^T` + owner + avatar_of mirrors become the
		// exception (genuinely game-shaped bookkeeping), not the tax. A
		// hand-written proc of the same name suppresses that accessor
		// (resolve_census) and keeps its own meaning.
		for e in s.entities {
			tsnake := to_snake(e.target)
			if e.gen_of || e.gen_owned || e.gen_my || e.gen_ids {
				fmt.sbprintf(
					b,
					"// Census for %s: %s_of(id), my_%s(), %s_owned_by(player), %s_ids() —\n// no game-side maps for the common shape.\n",
					e.target, tsnake, tsnake, tsnake, tsnake,
				)
			}
			if e.gen_of {
				fmt.sbprintf(
					b,
					"%s_of :: proc(b: ^kboot.Boot, id: knet.Net_Id) -> (^%s, bool) {{\n\te, ok := kboot.boot_entity(b, id, %s_TYPE)\n\treturn cast(^%s)e, ok\n}}\n\n",
					tsnake, e.target, strings.to_upper(tsnake), e.target,
				)
			}
			if e.gen_owned {
				fmt.sbprintf(
					b,
					"%s_owned_by :: proc(b: ^kboot.Boot, owner: knet.Player_Id) -> (^%s, bool) {{\n\te, _, ok := kboot.boot_owned_entity(b, %s_TYPE, owner)\n\treturn cast(^%s)e, ok\n}}\n\n",
					tsnake, e.target, strings.to_upper(tsnake), e.target,
				)
			}
			if e.gen_my {
				my_body :=
					e.gen_owned \
					? fmt.tprintf("return %s_owned_by(b, b.ses.me)", tsnake) \
					: fmt.tprintf("e, _, ok := kboot.boot_owned_entity(b, %s_TYPE, b.ses.me)\n\treturn cast(^%s)e, ok", strings.to_upper(tsnake), e.target)
				fmt.sbprintf(
					b,
					"my_%s :: proc(b: ^kboot.Boot) -> (^%s, bool) {{\n\t%s\n}}\n\n",
					tsnake, e.target, my_body,
				)
			}
			if e.gen_ids {
				fmt.sbprintf(
					b,
					"%s_ids :: proc(b: ^kboot.Boot, allocator := context.temp_allocator) -> []knet.Net_Id {{\n\treturn kboot.boot_entity_ids(b, %s_TYPE, allocator)\n}}\n\n",
					tsnake, strings.to_upper(tsnake),
				)
			}
		}
	}

	// lifecycle literal
	lc_lit := strings.builder_make()
	defer strings.builder_destroy(&lc_lit)
	if len(s.lifecycles) > 0 {
		strings.write_string(&lc_lit, "rt.Lifecycle{")
		for lc, i in s.lifecycles {
			if i > 0 {strings.write_string(&lc_lit, ", ")}
			fmt.sbprintf(&lc_lit, "%s = _%s_lc_%s", lc.keyword, snake, lc.keyword)
		}
		strings.write_string(&lc_lit, "}")
	}

	// @(init) registration. rt.register_class walks the struct's TYPE INFO (field
	// offsets/sizes/types + the gd:"..." tags) to build the Export/Onready tables at
	// startup; Class_Info carries only what reflection cannot see.
	fmt.sbprintf(b, "@(init)\n_register_%s :: proc \"contextless\" () {{\n", snake)
	fmt.sbprintf(b, "\trt.register_class(\n\t\t%s,\n", cls)
	w(b, "\t\trt.Class_Info {\n")
	fmt.sbprintf(b, "\t\t\tname = %q,\n", s.class_name)
	fmt.sbprintf(b, "\t\t\tbase = %q,\n", s.base)
	if len(s.lifecycles) > 0 {
		fmt.sbprintf(b, "\t\t\tlifecycle = %s,\n", strings.to_string(lc_lit))
	}
	// C-shaped member tables: pointer + count into the static backing arrays above.
	// An absent table stays at the Class_Info zero value (nil + 0).
	if len(s.methods) > 0 {
		fmt.sbprintf(b, "\t\t\tmethods = raw_data(_%s_methods[:]),\n", snake)
		fmt.sbprintf(b, "\t\t\tmethods_count = %d,\n", len(s.methods))
	}
	if len(s.connections) > 0 {
		fmt.sbprintf(b, "\t\t\tconnections = raw_data(_%s_connections[:]),\n", snake)
		fmt.sbprintf(b, "\t\t\tconnections_count = %d,\n", len(s.connections))
	}
	if len(s.rpcs) > 0 {
		fmt.sbprintf(b, "\t\t\trpcs = raw_data(_%s_rpcs[:]),\n", snake)
		fmt.sbprintf(b, "\t\t\trpcs_count = %d,\n", len(s.rpcs))
	}
	if len(s.exports) > 0 {
		fmt.sbprintf(b, "\t\t\tfields = raw_data(_%s_fields[:]),\n", snake)
		fmt.sbprintf(b, "\t\t\tfields_count = %d,\n", len(s.exports))
	}
	if s.tool {
		w(b, "\t\t\ttool = true,\n")
	}
	if s.icon != "" {
		fmt.sbprintf(b, "\t\t\ticon = %q,\n", s.icon)
	}
	if s.doc != "" {
		fmt.sbprintf(b, "\t\t\tdoc = %q,\n", s.doc)
	}
	w(b, "\t\t},\n")
	w(b, "\t)\n}\n")
}
