package scriptgen

import "core:fmt"
import "core:strings"

// Maps a Variant enum member like ".Int" to the bare token used to build cached
// constructor variable names (`_to_Int`, `_from_Int`).
ctor_tag :: proc(enum_name: string) -> string {
	return enum_name[1:] // drop leading '.'
}

// ---- main emitter ------------------------------------------------------------

generate :: proc(s: ^Script) -> string {
	b := strings.builder_make()
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)

	w(&b, "// Code generated by scriptgen. DO NOT EDIT.\n")
	fmt.sbprintf(&b, "// Source: %s.odin\n", snake)
	fmt.sbprintf(&b, "package %s\n\n", s.pkg)
	w(&b, "import gd \"godot:godot\"\n")
	w(&b, "import \"godot:gdext\"\n")
	w(&b, "import rt \"godot:runtime\"\n")
	// The trampolines/lifecycle wrappers establish `context = rt.script_context()` before
	// calling the user's plain Odin procs. On native that is `runtime.default_context()`
	// (heap-backed); on web the core installs an engine-backed context with a working
	// temp allocator (the freestanding default context has none). See runtime/context.odin.
	w(&b, "\n")

	// ---- cached Variant constructors used by trampolines ----
	to_set, from_set := collect_ctors(s)
	// Every method/accessor trampoline opens with `_ensure_ctors()`, so its definition must
	// exist whenever ANY such trampoline is emitted — even if no arg/return needs a Variant
	// constructor (a zero-arg `@(gd_method)` on a script with no other ctor needs). In that
	// case the proc is a cheap no-op; without it the call is an undeclared-name error.
	has_trampoline := len(s.methods) > 0
	if !has_trampoline {
		for ex in s.exports {
			if ex.getter != "" || ex.setter != "" {has_trampoline = true; break}
		}
	}
	if len(to_set) > 0 || len(from_set) > 0 || has_trampoline {
		w(&b, "// ---- cached Variant constructors ----\n")
		for tag in to_set {
			fmt.sbprintf(&b, "@(private = \"file\")\n_to_%s: gdext.TypeFromVariantConstructorProc\n", tag)
		}
		for tag in from_set {
			fmt.sbprintf(&b, "@(private = \"file\")\n_from_%s: gdext.VariantFromTypeConstructorProc\n", tag)
		}
		w(&b, "@(private = \"file\")\n_ctors_ready: bool\n")
		w(&b, "@(private = \"file\")\n_ensure_ctors :: proc \"contextless\" () {\n")
		w(&b, "\tif _ctors_ready {return}\n")
		for tag in to_set {
			fmt.sbprintf(&b, "\t_to_%s = gdext.get_variant_to_type_constructor(.%s)\n", tag, tag)
		}
		for tag in from_set {
			fmt.sbprintf(&b, "\t_from_%s = gdext.get_variant_from_type_constructor(.%s)\n", tag, tag)
		}
		w(&b, "\t_ctors_ready = true\n}\n\n")
	}

	// ---- lifecycle wrappers (plain proc -> rt.Lifecycle `proc \"c\"`) ----
	for lc in s.lifecycles {
		fname := fmt.tprintf("_%s_lc_%s", snake, lc.keyword)
		if lc.keyword == "process" || lc.keyword == "physics_process" {
			fmt.sbprintf(&b, "@(private = \"file\")\n%s :: proc \"c\" (self_raw: rawptr, delta: f64) {{\n", fname)
			w(&b, "\tcontext = rt.script_context()\n")
			if lc.has_delta {
				fmt.sbprintf(&b, "\t%s(cast(^%s)self_raw, delta)\n}}\n\n", lc.proc_name, cls)
			} else {
				fmt.sbprintf(&b, "\t%s(cast(^%s)self_raw)\n}}\n\n", lc.proc_name, cls)
			}
		} else {
			fmt.sbprintf(&b, "@(private = \"file\")\n%s :: proc \"c\" (self_raw: rawptr) {{\n", fname)
			w(&b, "\tcontext = rt.script_context()\n")
			fmt.sbprintf(&b, "\t%s(cast(^%s)self_raw)\n}}\n\n", lc.proc_name, cls)
		}
	}

	// ---- method trampolines ----
	for m in s.methods {
		emit_method_trampoline(&b, s, m)
	}

	// ---- getter/setter wrappers (richer-authoring #4) ----
	for ex in s.exports {
		if ex.getter != "" || ex.setter != "" {
			emit_accessor_wrappers(&b, s, ex)
		}
	}

	// ---- typed signal emit helpers ----
	if len(s.signals) > 0 {
		emit_signal_helpers(&b, s)
	}

	// ---- backing arrays + registration ----
	emit_registration(&b, s)

	return strings.to_string(b)
}

// to_/from_ constructor tag sets needed across all methods.
collect_ctors :: proc(s: ^Script) -> (to_set: [dynamic]string, from_set: [dynamic]string) {
	add :: proc(set: ^[dynamic]string, tag: string) {
		for e in set {if e == tag {return}}
		append(set, tag)
	}
	for m in s.methods {
		for a in m.args {
			add(&to_set, ctor_tag(a.vi.enum_name))
		}
		if m.ret.kind != .Nil {
			add(&from_set, ctor_tag(m.ret.enum_name))
		}
	}
	// getter/setter wrappers (richer-authoring #4): a getter marshals field->Variant
	// (from_), a setter marshals Variant->field (to_).
	for ex in s.exports {
		if ex.getter != "" {
			add(&from_set, ctor_tag(ex.vi.enum_name))
		}
		if ex.setter != "" {
			add(&to_set, ctor_tag(ex.vi.enum_name))
		}
	}
	return
}

emit_method_trampoline :: proc(b: ^strings.Builder, s: ^Script, m: Method_Info) {
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)
	fname := fmt.tprintf("_%s_m_%s", snake, m.gd_name)

	fmt.sbprintf(b, "// %s(", m.gd_name)
	for a, i in m.args {
		if i > 0 {w(b, ", ")}
		fmt.sbprintf(b, "%s: %s", a.name, a.type_text)
	}
	w(b, ")")
	if m.ret.kind != .Nil {fmt.sbprintf(b, " -> %s", m.ret.enum_name)}
	w(b, "\n")

	fmt.sbprintf(b, "@(private = \"file\")\n%s :: proc \"c\" (self_raw: rawptr, args: [^]gdext.VariantPtr, argc: i64, ret: gdext.VariantPtr) {{\n", fname)
	// Arity guard (dll-boundary defense in depth; the core's inst_call checks too): the
	// unpack below reads exactly this many Variants — a short call must not read past them.
	if len(m.args) > 0 {
		fmt.sbprintf(b, "\tif argc < %d {{return}}\n", len(m.args))
	}
	w(b, "\tcontext = rt.script_context()\n")
	w(b, "\t_ensure_ctors()\n")
	fmt.sbprintf(b, "\tself := cast(^%s)self_raw\n", cls)

	// Unpack args.
	call_args := make([dynamic]string)
	for a, i in m.args {
		tag := ctor_tag(a.vi.enum_name)
		switch a.vi.kind {
		case .Int:
			fmt.sbprintf(b, "\t_a%d: i64\n\t_to_%s(&_a%d, args[%d])\n", i, tag, i, i)
			append(&call_args, fmt.tprintf("%s(_a%d)", a.type_text, i))
		case .Float:
			fmt.sbprintf(b, "\t_a%d: f64\n\t_to_%s(&_a%d, args[%d])\n", i, tag, i, i)
			append(&call_args, fmt.tprintf("%s(_a%d)", a.type_text, i))
		case .Bool:
			fmt.sbprintf(b, "\t_a%d: bool\n\t_to_%s(&_a%d, args[%d])\n", i, tag, i, i)
			append(&call_args, fmt.tprintf("_a%d", i))
		case .Other:
			fmt.sbprintf(b, "\t_a%d: %s\n\t_to_%s(&_a%d, args[%d])\n", i, a.type_text, tag, i, i)
			append(&call_args, fmt.tprintf("_a%d", i))
		case .Nil:
		}
	}

	// Call the user proc.
	args_joined := strings.join(call_args[:], ", ")
	defer delete(args_joined)
	prefix := "self"
	if len(call_args) > 0 {
		prefix = fmt.tprintf("self, %s", args_joined)
	}
	if m.ret.kind == .Nil {
		fmt.sbprintf(b, "\t%s(%s)\n", m.proc_name, prefix)
	} else {
		fmt.sbprintf(b, "\t_r := %s(%s)\n", m.proc_name, prefix)
		tag := ctor_tag(m.ret.enum_name)
		switch m.ret.kind {
		case .Int:
			fmt.sbprintf(b, "\t_rv := i64(_r)\n\t_from_%s(ret, &_rv)\n", tag)
		case .Float:
			fmt.sbprintf(b, "\t_rv := f64(_r)\n\t_from_%s(ret, &_rv)\n", tag)
		case .Bool, .Other:
			fmt.sbprintf(b, "\t_rv := _r\n\t_from_%s(ret, &_rv)\n", tag)
		case .Nil:
		}
	}
	w(b, "}\n\n")
}

// Getter/setter wrappers (richer-authoring #4). A getter wrapper marshals the author's
// `get_<x>(self) -> V` result into the out-Variant; a setter wrapper unpacks the in-Variant
// into a typed value and calls `set_<x>(self, v)`. These are the proc ptrs the core's
// inst_get/inst_set call instead of raw field access. Marshalling mirrors the method
// trampoline's arg/return conventions.
emit_accessor_wrappers :: proc(b: ^strings.Builder, s: ^Script, ex: Export_Info) {
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)
	tag := ctor_tag(ex.vi.enum_name)

	if ex.getter != "" {
		fmt.sbprintf(b, "// getter for @export `%s` -> %s\n", ex.name, ex.getter)
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_get_%s :: proc \"c\" (self_raw: rawptr, ret: gdext.VariantPtr) {{\n", snake, ex.name)
		w(b, "\tcontext = rt.script_context()\n")
		w(b, "\t_ensure_ctors()\n")
		fmt.sbprintf(b, "\tself := cast(^%s)self_raw\n", cls)
		fmt.sbprintf(b, "\t_r := %s(self)\n", ex.getter)
		switch ex.vi.kind {
		case .Int:
			fmt.sbprintf(b, "\t_rv := i64(_r)\n\t_from_%s(ret, &_rv)\n", tag)
		case .Float:
			fmt.sbprintf(b, "\t_rv := f64(_r)\n\t_from_%s(ret, &_rv)\n", tag)
		case .Bool, .Other:
			fmt.sbprintf(b, "\t_rv := _r\n\t_from_%s(ret, &_rv)\n", tag)
		case .Nil:
		}
		w(b, "}\n\n")
	}

	if ex.setter != "" {
		fmt.sbprintf(b, "// setter for @export `%s` -> %s\n", ex.name, ex.setter)
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_set_%s :: proc \"c\" (self_raw: rawptr, value: gdext.VariantPtr) {{\n", snake, ex.name)
		w(b, "\tcontext = rt.script_context()\n")
		w(b, "\t_ensure_ctors()\n")
		fmt.sbprintf(b, "\tself := cast(^%s)self_raw\n", cls)
		switch ex.vi.kind {
		case .Int:
			fmt.sbprintf(b, "\t_v: i64\n\t_to_%s(&_v, value)\n", tag)
			fmt.sbprintf(b, "\t%s(self, %s(_v))\n", ex.setter, ex.type_text)
		case .Float:
			fmt.sbprintf(b, "\t_v: f64\n\t_to_%s(&_v, value)\n", tag)
			fmt.sbprintf(b, "\t%s(self, %s(_v))\n", ex.setter, ex.type_text)
		case .Bool:
			fmt.sbprintf(b, "\t_v: bool\n\t_to_%s(&_v, value)\n", tag)
			fmt.sbprintf(b, "\t%s(self, _v)\n", ex.setter)
		case .Other:
			fmt.sbprintf(b, "\t_v: %s\n\t_to_%s(&_v, value)\n", ex.type_text, tag)
			fmt.sbprintf(b, "\t%s(self, _v)\n", ex.setter)
		case .Nil:
		}
		w(b, "}\n\n")
	}
}

// Typed emit helpers, one per signal FIELD: `<snake>_emit_<field>(self, payload…)`. Thin
// wrappers over the godot package's `gd.emit`/`gd.emit_args` (which own the emit_signal
// MethodBind caching + CallError handling); the value they add is the TYPED signature —
// the field name and payload types are compile-checked at every emit site. The returned
// Error surfaces a misspelled/unregistered signal; callers are free to ignore it.
emit_signal_helpers :: proc(b: ^strings.Builder, s: ^Script) {
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)

	w(b, "// ---- typed signal emit helpers (over gd.emit/gd.emit_args) ----\n")
	for sig in s.signals {
		fmt.sbprintf(b, "// emit the `%s` signal (declared by the %s.%s field) with its payload.\n", sig.name, cls, sig.name)
		fmt.sbprintf(b, "%s_emit_%s :: proc \"contextless\" (self: ^%s", snake, sig.name, cls)
		for a in sig.args {
			fmt.sbprintf(b, ", %s: %s", a.name, a.vi.native)
		}
		w(b, ") -> gd.Error {\n")
		if len(sig.args) == 0 {
			fmt.sbprintf(b, "\treturn gd.emit(self.owner, \"%s\")\n", sig.name)
		} else {
			for a, i in sig.args {
				fmt.sbprintf(b, "\t_v%d := %s\n\t_va%d := gd.variant_from(&_v%d)\n", i, a.name, i, i)
			}
			fmt.sbprintf(b, "\t_err := gd.emit_args(self.owner, \"%s\"", sig.name)
			for i in 0 ..< len(sig.args) {
				fmt.sbprintf(b, ", _va%d", i)
			}
			w(b, ")\n")
			for i in 0 ..< len(sig.args) {
				fmt.sbprintf(b, "\tgdext.variant_destroy(&_va%d)\n", i)
			}
			w(b, "\treturn _err\n")
		}
		w(b, "}\n\n")
	}
}

emit_registration :: proc(b: ^strings.Builder, s: ^Script) {
	w :: strings.write_string
	cls := s.struct_name
	snake := to_snake(cls)

	w(b, "// ---- registration ----\n")

	// Per-export field metadata reflection cannot see: source line, `///` doc, and the
	// getter/setter WRAPPER proc pointers for `get=`/`set=` tags. The Export/Onready
	// tables themselves are built at registration by the runtime reflection walk
	// (rt.register_class -> runtime/register_class.odin).
	if len(s.exports) > 0 {
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_fields := [?]rt.Field_Meta {{\n", snake)
		for ex in s.exports {
			fmt.sbprintf(b, "\t{{field = \"%s\", line = %d", ex.name, ex.line)
			if ex.doc != "" {
				// %q — user-authored text can carry quotes/backslashes.
				fmt.sbprintf(b, ", doc = %q", ex.doc)
			}
			if ex.getter != "" {
				fmt.sbprintf(b, ", getter = _%s_get_%s", snake, ex.name)
			}
			if ex.setter != "" {
				fmt.sbprintf(b, ", setter = _%s_set_%s", snake, ex.name)
			}
			w(b, "},\n")
		}
		w(b, "}\n\n")
	}

	// per-method arg-type arrays
	for m in s.methods {
		if len(m.args) == 0 {continue}
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_%s_args := [?]gdext.Variant_Type{{", snake, m.gd_name)
		for a, i in m.args {
			if i > 0 {w(b, ", ")}
			w(b, a.vi.enum_name)
		}
		w(b, "}\n")
	}
	if len(s.methods) > 0 {
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_methods := [?]rt.Method {{\n", snake)
		for m in s.methods {
			// C-shaped table: pointer + count into the static per-method arg-type array.
			// An empty arg list stays at the zero value (nil + 0).
			args_ref := ""
			if len(m.args) > 0 {
				args_ref = fmt.tprintf(
					"arg_types = raw_data(_%s_%s_args[:]), arg_types_count = %d, ",
					snake,
					m.gd_name,
					len(m.args),
				)
			}
			fmt.sbprintf(
				b,
				"\t{{name = \"%s\", trampoline = _%s_m_%s, %sreturn_type = %s}},\n",
				m.gd_name,
				snake,
				m.gd_name,
				args_ref,
				m.ret.enum_name,
			)
		}
		w(b, "}\n\n")
	}

	// (No signal tables: signals are declared by typed struct fields, so the runtime
	// reflection walk builds the rt.Signal tables itself at registration.)

	// connections (@(gd_connect="signal") declarations)
	if len(s.connections) > 0 {
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_connections := [?]rt.Connection {{\n", snake)
		for c in s.connections {
			fmt.sbprintf(b, "\t{{signal = \"%s\", method = \"%s\"}},\n", c.signal, c.method)
		}
		w(b, "}\n\n")
	}

	// rpcs (@(gd_rpc[="..."]) declarations) — per-method multiplayer RPC config.
	if len(s.rpcs) > 0 {
		fmt.sbprintf(b, "@(private = \"file\")\n_%s_rpcs := [?]rt.Rpc {{\n", snake)
		for r in s.rpcs {
			fmt.sbprintf(
				b,
				"\t{{method = \"%s\", mode = %d, transfer = %d, call_local = %v, channel = %d}},\n",
				r.method,
				r.mode,
				r.transfer,
				r.call_local,
				r.channel,
			)
		}
		w(b, "}\n\n")
	}

	// lifecycle literal
	lc_lit := strings.builder_make()
	defer strings.builder_destroy(&lc_lit)
	if len(s.lifecycles) > 0 {
		strings.write_string(&lc_lit, "rt.Lifecycle{")
		for lc, i in s.lifecycles {
			if i > 0 {strings.write_string(&lc_lit, ", ")}
			fmt.sbprintf(&lc_lit, "%s = _%s_lc_%s", lc.keyword, snake, lc.keyword)
		}
		strings.write_string(&lc_lit, "}")
	}

	// @(init) registration. rt.register_class walks the struct's TYPE INFO (field
	// offsets/sizes/types + the gd:"..." tags) to build the Export/Onready tables at
	// startup; Class_Info carries only what reflection cannot see.
	fmt.sbprintf(b, "@(init)\n_register_%s :: proc \"contextless\" () {{\n", snake)
	fmt.sbprintf(b, "\trt.register_class(\n\t\t%s,\n", cls)
	w(b, "\t\trt.Class_Info {\n")
	fmt.sbprintf(b, "\t\t\tname = %q,\n", s.class_name)
	fmt.sbprintf(b, "\t\t\tbase = %q,\n", s.base)
	if len(s.lifecycles) > 0 {
		fmt.sbprintf(b, "\t\t\tlifecycle = %s,\n", strings.to_string(lc_lit))
	}
	// C-shaped member tables: pointer + count into the static backing arrays above.
	// An absent table stays at the Class_Info zero value (nil + 0).
	if len(s.methods) > 0 {
		fmt.sbprintf(b, "\t\t\tmethods = raw_data(_%s_methods[:]),\n", snake)
		fmt.sbprintf(b, "\t\t\tmethods_count = %d,\n", len(s.methods))
	}
	if len(s.connections) > 0 {
		fmt.sbprintf(b, "\t\t\tconnections = raw_data(_%s_connections[:]),\n", snake)
		fmt.sbprintf(b, "\t\t\tconnections_count = %d,\n", len(s.connections))
	}
	if len(s.rpcs) > 0 {
		fmt.sbprintf(b, "\t\t\trpcs = raw_data(_%s_rpcs[:]),\n", snake)
		fmt.sbprintf(b, "\t\t\trpcs_count = %d,\n", len(s.rpcs))
	}
	if len(s.exports) > 0 {
		fmt.sbprintf(b, "\t\t\tfields = raw_data(_%s_fields[:]),\n", snake)
		fmt.sbprintf(b, "\t\t\tfields_count = %d,\n", len(s.exports))
	}
	if s.tool {
		w(b, "\t\t\ttool = true,\n")
	}
	if s.icon != "" {
		fmt.sbprintf(b, "\t\t\ticon = %q,\n", s.icon)
	}
	if s.doc != "" {
		fmt.sbprintf(b, "\t\t\tdoc = %q,\n", s.doc)
	}
	w(b, "\t\t},\n")
	w(b, "\t)\n}\n")
}
