#+build wasm32, wasm64p32
package core

import rt "godot:runtime"
import "base:runtime"

// ----------------------------------------------------------------------------
// WEB scripts wiring. The scripts package + the `runtime` registry are linked INTO
// this same wasm module, so there is no dlopen/boot handshake and no hot reload.
// (Native equivalents live in scripts_native.odin, excluded from the wasm build.)
// ----------------------------------------------------------------------------

// The Odin `context` every compiled-script trampoline (lifecycle wrappers + method
// trampolines) runs under on web. `runtime.default_context()` is unusable for scripts on
// freestanding_wasm32 — its temp_allocator is nil (so `core:fmt`/temp allocations silently
// yield "", e.g. the HUD's label text) and its main allocator is Odin's own wasm allocator,
// which is unsafe in a shared SIDE_MODULE (memory.grow collides with Emscripten's heap).
// We start from the default context (logger/assertion/random) but swap BOTH allocators to
// the engine-backed, alignment-correct allocator (see web.odin), AND repoint
// `random_generator` at a persistent, pre-seeded package-global state (see below). scriptgen
// routes the trampolines here via rt.script_context() + the hook installed in web_startup.
//
// Note: temp allocations made here are not freed until the engine heap reclaims them; the
// showcase HUD only formats on a score CHANGE (guarded), so this is negligible.
@(private)
web_script_context :: proc "contextless" () -> runtime.Context {
	c := runtime.default_context()
	a := web_aligned_allocator()
	c.allocator = a
	c.temp_allocator = a
	// Make `core:math/rand` work in the browser. The default chacha8 generator carried by
	// runtime.default_context() lazily self-seeds from the OS entropy source on first use —
	// but freestanding_wasm32 has none (runtime.HAS_RAND_BYTES == false), so that path hits
	// `panic_contextless("no runtime entropy source")` -> wasm `unreachable` trap on EVERY
	// rand call. Point the context at our own state, which web_startup seeds up front, so it
	// is already `_seeded` and never reaches the entropy path. One shared global state ->
	// the sequence ADVANCES across script calls instead of restarting each invocation.
	// (Native is unaffected: scripts_native.odin never touches random_generator, so native
	// scripts keep runtime.default_context()'s OS-seeded generator.)
	c.random_generator = runtime.default_random_generator(&web_random_state)
	return c
}

// Persistent PRNG state backing `context.random_generator` for compiled scripts on web.
// Seeded once in web_startup with a fixed NON-ZERO constant (a zero state leaves some PRNGs
// degenerate). freestanding_wasm32 has no cheap entropy source, so the seed is constant and
// WEB RUNS ARE DETERMINISTIC — the same rand sequence on every page load. If you need
// per-run variation, reseed `web_random_state` here from a real source (e.g. an engine time
// source via the binding) once the engine is up.
@(private)
WEB_RANDOM_SEED :: 0x9E3779B97F4A7C15 // golden-ratio constant; non-zero

@(private)
web_random_state: runtime.Default_Random_State

// A SIDE_MODULE has no CRT / entry point, so the Odin `@(init)` chain is not run
// automatically. `odin_godot_init` calls this to run it explicitly — which fires each
// script's `@(init) rt.register(...)` self-registration into the shared registry.
// (`__$startup_runtime` is generated by the compiler from all `@(init)` procs.) We also
// install the web script context hook so allocating scripts work in the browser.
web_startup :: proc "contextless" () {
	rt.script_context_hook = web_script_context
	context = runtime.default_context()
	// Seed the script PRNG once, before any script context is used, so core:math/rand works
	// in the browser without an OS entropy source (see web_script_context above). reset_u64
	// drives the generator's .Reset mode, marking the state `_seeded`.
	runtime.random_generator_reset_u64(runtime.default_random_generator(&web_random_state), WEB_RANDOM_SEED)
	runtime._startup_runtime()
}

// Read the manifest directly (same module — no dlsym). The registrations have already
// run via web_startup, so the registry is populated.
@(private)
odin_scripts_load :: proc() {
	// Single module on web: wire the typed cross-script resolver directly (no dlsym).
	rt.odin_scripts_set_core_api(odin_script_struct)
	descs, n := rt.odin_scripts_manifest()
	index_scripts_manifest(descs, n)
}

// No hot reload in the browser (no compiler, no dlopen). Always reports failure.
@(private)
odin_scripts_reload :: proc() -> bool {
	return false
}

// No editor / compiler / filesystem in the browser, so the rebuild-on-save coordinator
// (native core/reload.odin) does not exist here. `OdinScript._reload` references this on
// all platforms; on web it is a no-op (the editor-hint branch is never taken anyway).
@(private)
reload_request :: proc() {
}
