#+build windows
package core

// Windows counterpart of core/debug_launch.odin. No terminal-lldb items (that pipeline
// is dSYM/osascript-shaped); Windows native debugging is Visual Studio / VS Code's
// cppvsdbg / WinDbg against the .pdb files the -debug builds already emit. What IS
// wired: "Generate VS Code Debug Config" — a cppvsdbg launch.json (ships with the
// standard C/C++ extension). Simpler than the macOS flow: no SIP, so the config debugs
// the editor's own binary directly, no re-signed copy, no preLaunchTask.

import "godot:gdext"
import "godot:godot"

import "base:runtime"
import "core:fmt"
import "core:os"

@(private)
debug_register_menu_items :: proc(plug: godot.Editor_Plugin) {
	vs_name := godot.new_string_cstring("Generate VS Code Debug Config")
	godot.editor_plugin_add_tool_menu_item(plug, vs_name, make_menu_callable(vscode_menu_call_windows))
}

@(private = "file")
write_if_absent_w :: proc(path: string, content: string) -> bool {
	if os.exists(path) {
		editor_msg_warn(fmt.tprintf("odin_godot: %s already exists — leaving it untouched.", path))
		return false
	}
	if werr := os.write_entire_file(path, transmute([]byte)content); werr != nil {
		editor_msg_error(fmt.tprintf("odin_godot: couldn't write %s.", path))
		return false
	}
	return true
}

@(private = "file")
vscode_menu_call_windows :: proc "c" (userdata: rawptr, args: [^]gdext.VariantPtr, argc: i64, ret: gdext.VariantPtr, err: ^gdext.CallError) {
	context = gdext.godot_context()
	context.allocator = runtime.heap_allocator()
	if err != nil {err.error = .Ok}

	exe := string_to_odin(godot.os_get_executable_path(godot.singleton_os()), context.temp_allocator)
	gres := godot.new_string_cstring("res://")
	pg := godot.project_settings_globalize_path(godot.singleton_project_settings(), gres)
	proj := string_to_odin(pg, context.temp_allocator)
	if len(proj) > 0 && (proj[len(proj) - 1] == '/' || proj[len(proj) - 1] == '\\') {
		proj = proj[:len(proj) - 1]
	}

	vsdir := fmt.tprintf("%s/.vscode", proj)
	if !os.exists(vsdir) {
		if mkerr := os.make_directory(vsdir); mkerr != nil {
			editor_msg_error(fmt.tprintf("odin_godot: couldn't create %s.", vsdir))
			return
		}
	}

	// JSON strings need escaped backslashes for the Windows exe path.
	exe_json := make([dynamic]byte, 0, len(exe) * 2, context.temp_allocator)
	for i in 0 ..< len(exe) {
		if exe[i] == '\\' {append(&exe_json, '\\')}
		append(&exe_json, exe[i])
	}

	launch := fmt.tprintf(
		`{{
    // Debug the Godot game with native Odin-script breakpoints (requires the standard
    // "C/C++" extension, ms-vscode.cpptools). Generated by odin_godot - Project >
    // Tools > Generate VS Code Debug Config. Set breakpoints directly in your .odin
    // files; the .pdb files the script builds emit carry full symbols + lines.
    "version": "0.2.0",
    "configurations": [
        {{
            "type": "cppvsdbg",
            "request": "launch",
            "name": "Debug Godot Game (Odin)",
            "program": "%s",
            "args": ["--path", "${{workspaceFolder}}"],
            "cwd": "${{workspaceFolder}}"
        }}
    ]
}}
`,
		string(exe_json[:]),
	)
	if write_if_absent_w(fmt.tprintf("%s/launch.json", vsdir), launch) {
		godot.print_str(
			fmt.tprintf(
				"odin_godot: wrote %s/launch.json — install the C/C++ extension (ms-vscode.cpptools), open the project in VS Code, set breakpoints in .odin files, F5.",
				vsdir,
			),
		)
	}
}
